
=encoding utf8

=head1 NAME

Sidef::Types::Number::Quaternion

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Quaternion(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Number::Number

=head1 METHODS

=head2 !=

I<Obj> B<!=> I<Obj> -> I<Obj>

Return the

Aliases: I<ne>

=cut

=head2 %

I<Obj> B<%> I<Obj> -> I<Obj>

Return the

Aliases: I<mod>

=cut

=head2 &

I<Obj> B<&> I<Obj> -> I<Obj>

Return the

Aliases: I<and>

=cut

=head2 *

I<Obj> B<*> I<Obj> -> I<Obj>

Return the

Aliases: I<mul>

=cut

=head2 **

I<Obj> B<**> I<Obj> -> I<Obj>

Return the

Aliases: I<pow>

=cut

=head2 +

I<Obj> B<+> I<Obj> -> I<Obj>

Return the

Aliases: I<add>

=cut

=head2 ++

I<Obj> B<++> I<Obj> -> I<Obj>

Return the

Aliases: I<inc>

=cut

=head2 -

I<Obj> B<-> I<Obj> -> I<Obj>

Return the

Aliases: I<sub>

=cut

=head2 --

I<Obj> B<--> I<Obj> -> I<Obj>

Return the

Aliases: I<dec>

=cut

=head2 /

I<Obj> B</> I<Obj> -> I<Obj>

Return the

Aliases: I<÷>, I<div>

=cut

=head2 <

I<Obj> B<E<lt>> I<Obj> -> I<Obj>

Return the

Aliases: I<lt>

=cut

=head2 <<

I<Obj> B<E<lt>E<lt>> I<Obj> -> I<Obj>

Return the

Aliases: I<lsft>, I<shift_left>

=cut

=head2 <=>

I<Obj> B<E<lt>=E<gt>> I<Obj> -> I<Obj>

Return the

Aliases: I<cmp>

=cut

=head2 ==

I<Obj> B<==> I<Obj> -> I<Obj>

Return the

Aliases: I<eq>

=cut

=head2 >

I<Obj> B<E<gt>> I<Obj> -> I<Obj>

Return the

Aliases: I<gt>

=cut

=head2 >>

I<Obj> B<E<gt>E<gt>> I<Obj> -> I<Obj>

Return the

Aliases: I<rsft>, I<shift_right>

=cut

=head2 ^

I<Obj> B<^> I<Obj> -> I<Obj>

Return the

Aliases: I<xor>

=cut

=head2 |

I<Obj> B<|> I<Obj> -> I<Obj>

Return the

Aliases: I<or>

=cut

=head2 ≤

I<Obj> B<≤> I<Obj> -> I<Obj>

Return the

Aliases: I<E<lt>=>, I<le>

=cut

=head2 ≥

I<Obj> B<≥> I<Obj> -> I<Obj>

Return the

Aliases: I<E<gt>=>, I<ge>

=cut

=head2 a

Quaternion.a() -> I<Obj>

Return the

=cut

=head2 abs

Quaternion.abs() -> I<Obj>

Return the

=cut

=head2 b

Quaternion.b() -> I<Obj>

Return the

=cut

=head2 c

Quaternion.c() -> I<Obj>

Return the

=cut

=head2 ceil

Quaternion.ceil() -> I<Obj>

Return the

=cut

=head2 conj

Quaternion.conj() -> I<Obj>

Return the

=cut

=head2 d

Quaternion.d() -> I<Obj>

Return the

=cut

=head2 dump

Quaternion.dump() -> I<Obj>

Return the

=cut

=head2 float

Quaternion.float() -> I<Obj>

Return the

=cut

=head2 floor

Quaternion.floor() -> I<Obj>

Return the

=cut

=head2 inv

Quaternion.inv() -> I<Obj>

Return the

=cut

=head2 invmod

Quaternion.invmod() -> I<Obj>

Return the

=cut

=head2 is_coprime

Quaternion.is_coprime() -> I<Obj>

Return the

=cut

=head2 is_mone

Quaternion.is_mone() -> I<Obj>

Return the

=cut

=head2 is_one

Quaternion.is_one() -> I<Obj>

Return the

=cut

=head2 is_zero

Quaternion.is_zero() -> I<Obj>

Return the

=cut

=head2 neg

Quaternion.neg() -> I<Obj>

Return the

=cut

=head2 new

Quaternion.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 norm

Quaternion.norm() -> I<Obj>

Return the

=cut

=head2 parts

Quaternion.parts() -> I<Obj>

Return the

=cut

=head2 powmod

Quaternion.powmod() -> I<Obj>

Return the

=cut

=head2 ratmod

Quaternion.ratmod() -> I<Obj>

Return the

=cut

=head2 reals

Quaternion.reals() -> I<Obj>

Return the

=cut

=head2 round

Quaternion.round() -> I<Obj>

Return the

=cut

=head2 sgn

Quaternion.sgn() -> I<Obj>

Return the

=cut

=head2 sqr

Quaternion.sqr() -> I<Obj>

Return the

=cut

=head2 to_c

Quaternion.to_c() -> I<Obj>

Return the

Aliases: I<to_n>

=cut

=head2 to_gauss

Quaternion.to_gauss() -> I<Obj>

Return the

=cut

=head2 to_s

Quaternion.to_s() -> I<Obj>

Return the

=cut
