
=encoding utf8

=head1 NAME

Sidef::Types::Set::Set

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Set(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Hash::Hash

=head1 METHODS

=head2 &

I<Obj> B<&> I<Obj> -> I<Obj>

Return the

Aliases: I<∩>, I<and>, I<intersection>

=cut

=head2 +

I<Obj> B<+> I<Obj> -> I<Obj>

Return the

Aliases: I<concat>

=cut

=head2 -

I<Obj> B<-> I<Obj> -> I<Obj>

Return the

Aliases: I<∖>, I<sub>, I<diff>, I<difference>

=cut

=head2 ...

I<Obj> B<...> I<Obj> -> I<Obj>

Return the

Aliases: I<to_list>

=cut

=head2 <<

I<Obj> B<E<lt>E<lt>> I<Obj> -> I<Obj>

Return the

Aliases: I<add>, I<push>, I<append>

=cut

=head2 ^

I<Obj> B<^> I<Obj> -> I<Obj>

Return the

Aliases: I<xor>, I<symdiff>, I<symmetric_difference>

=cut

=head2 collect

Set.collect() -> I<Obj>

Return the

=cut

=head2 contains_all

Set.contains_all() -> I<Obj>

Return the

=cut

=head2 count

Set.count() -> I<Obj>

Return the

=cut

=head2 count_by

Set.count_by() -> I<Obj>

Return the

=cut

=head2 delete

Set.delete() -> I<Obj>

Return the

Aliases: I<remove>, I<discard>

=cut

=head2 delete_first_if

Set.delete_first_if() -> I<Obj>

Return the

=cut

=head2 delete_if

Set.delete_if() -> I<Obj>

Return the

=cut

=head2 dump

Set.dump() -> I<Obj>

Return the

=cut

=head2 each

Set.each() -> I<Obj>

Return the

=cut

=head2 grep

Set.grep() -> I<Obj>

Return the

Aliases: I<select>

=cut

=head2 has

Set.has() -> I<Obj>

Return the

Aliases: I<exists>, I<has_key>, I<haskey>, I<contain>, I<include>, I<contains>, I<includes>

=cut

=head2 iter

Set.iter() -> I<Obj>

Return the

=cut

=head2 join

Set.join() -> I<Obj>

Return the

=cut

=head2 map

Set.map() -> I<Obj>

Return the

=cut

=head2 max

Set.max() -> I<Obj>

Return the

=cut

=head2 max_by

Set.max_by() -> I<Obj>

Return the

=cut

=head2 min

Set.min() -> I<Obj>

Return the

=cut

=head2 min_by

Set.min_by() -> I<Obj>

Return the

=cut

=head2 new

Set.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 pop

Set.pop() -> I<Obj>

Return the

=cut

=head2 shift

Set.shift() -> I<Obj>

Return the

=cut

=head2 sort

Set.sort() -> I<Obj>

Return the

=cut

=head2 sort_by

Set.sort_by() -> I<Obj>

Return the

=cut

=head2 to_a

Set.to_a() -> I<Obj>

Return the

Aliases: I<values>, I<to_array>

=cut

=head2 to_bag

Set.to_bag() -> I<Obj>

Return the

=cut

=head2 to_set

Set.to_set() -> I<Obj>

Return the

=cut

=head2 |

I<Obj> B<|> I<Obj> -> I<Obj>

Return the

Aliases: I<∪>, I<or>, I<union>

=cut

=head2 ≡

I<Obj> B<≡> I<Obj> -> I<Obj>

Return the

=cut

=head2 ≤

I<Obj> B<≤> I<Obj> -> I<Obj>

Return the

Aliases: I<⊆>, I<E<lt>=>, I<is_subset>

=cut

=head2 ≥

I<Obj> B<≥> I<Obj> -> I<Obj>

Return the

Aliases: I<⊇>, I<E<gt>=>, I<is_superset>

=cut
