---
abstract: 'The Sidef Programming Language'
author:
  - 'Daniel Șuteu   (<trizenx@gmail.com>)'
  - 'Ioana Fălcușan (<ioanaflavia@gmail.com>)'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sidef
provides:
  Sidef:
    file: lib/Sidef.pm
    version: '2.11'
  Sidef::Convert::Convert:
    file: lib/Sidef/Convert/Convert.pm
  Sidef::Deparse::Perl:
    file: lib/Sidef/Deparse/Perl.pm
  Sidef::Deparse::Sidef:
    file: lib/Sidef/Deparse/Sidef.pm
  Sidef::Eval::Eval:
    file: lib/Sidef/Eval/Eval.pm
  Sidef::Math::Math:
    file: lib/Sidef/Math/Math.pm
  Sidef::Meta::Assert:
    file: lib/Sidef/Meta/Assert.pm
  Sidef::Meta::Error:
    file: lib/Sidef/Meta/Error.pm
  Sidef::Meta::Warning:
    file: lib/Sidef/Meta/Warning.pm
  Sidef::Module::Func:
    file: lib/Sidef/Module/Func.pm
  Sidef::Module::OO:
    file: lib/Sidef/Module/OO.pm
  Sidef::Object::Object:
    file: lib/Sidef/Object/Object.pm
  Sidef::Object::Unary:
    file: lib/Sidef/Object/Unary.pm
  Sidef::Optimizer:
    file: lib/Sidef/Optimizer.pm
  Sidef::Parser:
    file: lib/Sidef/Parser.pm
  Sidef::Perl::Builtin:
    file: lib/Sidef/Perl/Builtin.pm
  Sidef::Perl::Perl:
    file: lib/Sidef/Perl/Perl.pm
  Sidef::Sys::SIG:
    file: lib/Sidef/Sys/SIG.pm
  Sidef::Sys::Sys:
    file: lib/Sidef/Sys/Sys.pm
  Sidef::Time::Gmtime:
    file: lib/Sidef/Time/Gmtime.pm
  Sidef::Time::Localtime:
    file: lib/Sidef/Time/Localtime.pm
  Sidef::Time::Time:
    file: lib/Sidef/Time/Time.pm
  Sidef::Types::Array::Array:
    file: lib/Sidef/Types/Array/Array.pm
  Sidef::Types::Array::HCArray:
    file: lib/Sidef/Types/Array/HCArray.pm
  Sidef::Types::Array::List:
    file: lib/Sidef/Types/Array/List.pm
  Sidef::Types::Array::MultiArray:
    file: lib/Sidef/Types/Array/MultiArray.pm
  Sidef::Types::Array::Pair:
    file: lib/Sidef/Types/Array/Pair.pm
  Sidef::Types::Black::Hole:
    file: lib/Sidef/Types/Black/Hole.pm
  Sidef::Types::Block::Break:
    file: lib/Sidef/Types/Block/Break.pm
  Sidef::Types::Block::Code:
    file: lib/Sidef/Types/Block/Code.pm
  Sidef::Types::Block::CodeInit:
    file: lib/Sidef/Types/Block/CodeInit.pm
  Sidef::Types::Block::Continue:
    file: lib/Sidef/Types/Block/Continue.pm
  Sidef::Types::Block::Default:
    file: lib/Sidef/Types/Block/Default.pm
  Sidef::Types::Block::Do:
    file: lib/Sidef/Types/Block/Do.pm
  Sidef::Types::Block::For:
    file: lib/Sidef/Types/Block/For.pm
  Sidef::Types::Block::ForArray:
    file: lib/Sidef/Types/Block/ForArray.pm
  Sidef::Types::Block::Fork:
    file: lib/Sidef/Types/Block/Fork.pm
  Sidef::Types::Block::Gather:
    file: lib/Sidef/Types/Block/Gather.pm
  Sidef::Types::Block::Given:
    file: lib/Sidef/Types/Block/Given.pm
  Sidef::Types::Block::If:
    file: lib/Sidef/Types/Block/If.pm
  Sidef::Types::Block::Loop:
    file: lib/Sidef/Types/Block/Loop.pm
  Sidef::Types::Block::Next:
    file: lib/Sidef/Types/Block/Next.pm
  Sidef::Types::Block::Return:
    file: lib/Sidef/Types/Block/Return.pm
  Sidef::Types::Block::Take:
    file: lib/Sidef/Types/Block/Take.pm
  Sidef::Types::Block::Try:
    file: lib/Sidef/Types/Block/Try.pm
  Sidef::Types::Block::When:
    file: lib/Sidef/Types/Block/When.pm
  Sidef::Types::Block::While:
    file: lib/Sidef/Types/Block/While.pm
  Sidef::Types::Bool::Bool:
    file: lib/Sidef/Types/Bool/Bool.pm
  Sidef::Types::Bool::Ternary:
    file: lib/Sidef/Types/Bool/Ternary.pm
  Sidef::Types::Byte::Byte:
    file: lib/Sidef/Types/Byte/Byte.pm
  Sidef::Types::Byte::Bytes:
    file: lib/Sidef/Types/Byte/Bytes.pm
  Sidef::Types::Char::Char:
    file: lib/Sidef/Types/Char/Char.pm
  Sidef::Types::Char::Chars:
    file: lib/Sidef/Types/Char/Chars.pm
  Sidef::Types::Glob::Backtick:
    file: lib/Sidef/Types/Glob/Backtick.pm
  Sidef::Types::Glob::Dir:
    file: lib/Sidef/Types/Glob/Dir.pm
  Sidef::Types::Glob::DirHandle:
    file: lib/Sidef/Types/Glob/DirHandle.pm
  Sidef::Types::Glob::File:
    file: lib/Sidef/Types/Glob/File.pm
  Sidef::Types::Glob::FileHandle:
    file: lib/Sidef/Types/Glob/FileHandle.pm
  Sidef::Types::Glob::Pipe:
    file: lib/Sidef/Types/Glob/Pipe.pm
  Sidef::Types::Glob::Socket:
    file: lib/Sidef/Types/Glob/Socket.pm
  Sidef::Types::Glob::SocketHandle:
    file: lib/Sidef/Types/Glob/SocketHandle.pm
  Sidef::Types::Glob::Stat:
    file: lib/Sidef/Types/Glob/Stat.pm
  Sidef::Types::Grapheme::Grapheme:
    file: lib/Sidef/Types/Grapheme/Grapheme.pm
  Sidef::Types::Grapheme::Graphemes:
    file: lib/Sidef/Types/Grapheme/Graphemes.pm
  Sidef::Types::Hash::Hash:
    file: lib/Sidef/Types/Hash/Hash.pm
  Sidef::Types::Nil::Nil:
    file: lib/Sidef/Types/Nil/Nil.pm
  Sidef::Types::Null::Null:
    file: lib/Sidef/Types/Null/Null.pm
  Sidef::Types::Number::Complex:
    file: lib/Sidef/Types/Number/Complex.pm
  Sidef::Types::Number::Number:
    file: lib/Sidef/Types/Number/Number.pm
  Sidef::Types::Range::RangeNumber:
    file: lib/Sidef/Types/Range/RangeNumber.pm
  Sidef::Types::Range::RangeString:
    file: lib/Sidef/Types/Range/RangeString.pm
  Sidef::Types::Regex::Match:
    file: lib/Sidef/Types/Regex/Match.pm
  Sidef::Types::Regex::Regex:
    file: lib/Sidef/Types/Regex/Regex.pm
  Sidef::Types::String::String:
    file: lib/Sidef/Types/String/String.pm
  Sidef::Variable::ClassInit:
    file: lib/Sidef/Variable/ClassInit.pm
  Sidef::Variable::Const:
    file: lib/Sidef/Variable/Const.pm
  Sidef::Variable::ConstInit:
    file: lib/Sidef/Variable/ConstInit.pm
  Sidef::Variable::Define:
    file: lib/Sidef/Variable/Define.pm
  Sidef::Variable::Global:
    file: lib/Sidef/Variable/Global.pm
  Sidef::Variable::Init:
    file: lib/Sidef/Variable/Init.pm
  Sidef::Variable::Label:
    file: lib/Sidef/Variable/Label.pm
  Sidef::Variable::LazyMethod:
    file: lib/Sidef/Variable/LazyMethod.pm
  Sidef::Variable::Local:
    file: lib/Sidef/Variable/Local.pm
  Sidef::Variable::Magic:
    file: lib/Sidef/Variable/Magic.pm
  Sidef::Variable::NamedParam:
    file: lib/Sidef/Variable/NamedParam.pm
  Sidef::Variable::Ref:
    file: lib/Sidef/Variable/Ref.pm
  Sidef::Variable::Static:
    file: lib/Sidef/Variable/Static.pm
  Sidef::Variable::Struct:
    file: lib/Sidef/Variable/Struct.pm
  Sidef::Variable::Variable:
    file: lib/Sidef/Variable/Variable.pm
requires:
  Cwd: '0'
  Encode: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec: '0'
  Getopt::Std: '0'
  List::Util: '1.33'
  Math::BigFloat: '0'
  Math::BigInt: '0'
  Math::BigRat: '0'
  Math::Complex: '0'
  Math::Trig: '0'
  Memoize: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Socket: '0'
  Storable: '0'
  Term::ReadLine: '0'
  Time::HiRes: '0'
  perl: v5.16.1
  utf8: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '2.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
