---
abstract: 'Sidef Programming Language'
author:
  - 'Daniel Șuteu   (<trizenx@gmail.com>)'
  - 'Ioana Fălcușan (<ioanaflavia@gmail.com>)'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sidef
provides:
  Sidef:
    file: lib/Sidef.pm
    version: '0.03'
  Sidef::Args::Args:
    file: lib/Sidef/Args/Args.pm
  Sidef::Convert::Convert:
    file: lib/Sidef/Convert/Convert.pm
  Sidef::Deparse::Perl:
    file: lib/Sidef/Deparse/Perl.pm
  Sidef::Deparse::Sidef:
    file: lib/Sidef/Deparse/Sidef.pm
  Sidef::Eval::Eval:
    file: lib/Sidef/Eval/Eval.pm
  Sidef::Exec:
    file: lib/Sidef/Exec.pm
  Sidef::Math::Math:
    file: lib/Sidef/Math/Math.pm
  Sidef::Module::Caller:
    file: lib/Sidef/Module/Caller.pm
  Sidef::Module::Func:
    file: lib/Sidef/Module/Func.pm
  Sidef::Module::Require:
    file: lib/Sidef/Module/Require.pm
  Sidef::Object::Object:
    file: lib/Sidef/Object/Object.pm
  Sidef::Object::Unary:
    file: lib/Sidef/Object/Unary.pm
  Sidef::Optimizer:
    file: lib/Sidef/Optimizer.pm
  Sidef::Parser:
    file: lib/Sidef/Parser.pm
  Sidef::Perl::Perl:
    file: lib/Sidef/Perl/Perl.pm
  Sidef::Sys::SIG:
    file: lib/Sidef/Sys/SIG.pm
  Sidef::Sys::Sys:
    file: lib/Sidef/Sys/Sys.pm
  Sidef::Time::Gmtime:
    file: lib/Sidef/Time/Gmtime.pm
  Sidef::Time::Localtime:
    file: lib/Sidef/Time/Localtime.pm
  Sidef::Time::Time:
    file: lib/Sidef/Time/Time.pm
  Sidef::Types::Array::Array:
    file: lib/Sidef/Types/Array/Array.pm
  Sidef::Types::Array::HCArray:
    file: lib/Sidef/Types/Array/HCArray.pm
  Sidef::Types::Array::MultiArray:
    file: lib/Sidef/Types/Array/MultiArray.pm
  Sidef::Types::Array::Pair:
    file: lib/Sidef/Types/Array/Pair.pm
  Sidef::Types::Array::Range:
    file: lib/Sidef/Types/Array/Range.pm
  Sidef::Types::Black::Hole:
    file: lib/Sidef/Types/Black/Hole.pm
  Sidef::Types::Block::Break:
    file: lib/Sidef/Types/Block/Break.pm
  Sidef::Types::Block::Code:
    file: lib/Sidef/Types/Block/Code.pm
  Sidef::Types::Block::Continue:
    file: lib/Sidef/Types/Block/Continue.pm
  Sidef::Types::Block::Do:
    file: lib/Sidef/Types/Block/Do.pm
  Sidef::Types::Block::For:
    file: lib/Sidef/Types/Block/For.pm
  Sidef::Types::Block::Fork:
    file: lib/Sidef/Types/Block/Fork.pm
  Sidef::Types::Block::Given:
    file: lib/Sidef/Types/Block/Given.pm
  Sidef::Types::Block::Next:
    file: lib/Sidef/Types/Block/Next.pm
  Sidef::Types::Block::PerlCode:
    file: lib/Sidef/Deparse/Perl.pm
  Sidef::Types::Block::Return:
    file: lib/Sidef/Types/Block/Return.pm
  Sidef::Types::Block::Switch:
    file: lib/Sidef/Types/Block/Switch.pm
  Sidef::Types::Block::Try:
    file: lib/Sidef/Types/Block/Try.pm
  Sidef::Types::Bool::Bool:
    file: lib/Sidef/Types/Bool/Bool.pm
  Sidef::Types::Bool::If:
    file: lib/Sidef/Types/Bool/If.pm
  Sidef::Types::Bool::Ternary:
    file: lib/Sidef/Types/Bool/Ternary.pm
  Sidef::Types::Bool::While:
    file: lib/Sidef/Types/Bool/While.pm
  Sidef::Types::Byte::Byte:
    file: lib/Sidef/Types/Byte/Byte.pm
  Sidef::Types::Byte::Bytes:
    file: lib/Sidef/Types/Byte/Bytes.pm
  Sidef::Types::Char::Char:
    file: lib/Sidef/Types/Char/Char.pm
  Sidef::Types::Char::Chars:
    file: lib/Sidef/Types/Char/Chars.pm
  Sidef::Types::Glob::Backtick:
    file: lib/Sidef/Types/Glob/Backtick.pm
  Sidef::Types::Glob::Dir:
    file: lib/Sidef/Types/Glob/Dir.pm
  Sidef::Types::Glob::DirHandle:
    file: lib/Sidef/Types/Glob/DirHandle.pm
  Sidef::Types::Glob::Fcntl:
    file: lib/Sidef/Types/Glob/Fcntl.pm
  Sidef::Types::Glob::File:
    file: lib/Sidef/Types/Glob/File.pm
  Sidef::Types::Glob::FileHandle:
    file: lib/Sidef/Types/Glob/FileHandle.pm
  Sidef::Types::Glob::Pipe:
    file: lib/Sidef/Types/Glob/Pipe.pm
  Sidef::Types::Glob::PipeHandle:
    file: lib/Sidef/Types/Glob/PipeHandle.pm
  Sidef::Types::Glob::Stat:
    file: lib/Sidef/Types/Glob/Stat.pm
  Sidef::Types::Hash::Hash:
    file: lib/Sidef/Types/Hash/Hash.pm
  Sidef::Types::Nil::Nil:
    file: lib/Sidef/Types/Nil/Nil.pm
  Sidef::Types::Number::Complex:
    file: lib/Sidef/Types/Number/Complex.pm
  Sidef::Types::Number::Number:
    file: lib/Sidef/Types/Number/Number.pm
  Sidef::Types::Regex::Matches:
    file: lib/Sidef/Types/Regex/Matches.pm
  Sidef::Types::Regex::Regex:
    file: lib/Sidef/Types/Regex/Regex.pm
  Sidef::Types::String::String:
    file: lib/Sidef/Types/String/String.pm
  Sidef::Variable::Class:
    file: lib/Sidef/Variable/Class.pm
  Sidef::Variable::ClassInit:
    file: lib/Sidef/Variable/ClassInit.pm
  Sidef::Variable::ClassVar:
    file: lib/Sidef/Variable/ClassVar.pm
  Sidef::Variable::Init:
    file: lib/Sidef/Variable/Init.pm
  Sidef::Variable::InitMy:
    file: lib/Sidef/Variable/InitMy.pm
  Sidef::Variable::LazyMethod:
    file: lib/Sidef/Variable/LazyMethod.pm
  Sidef::Variable::Magic:
    file: lib/Sidef/Variable/Magic.pm
  Sidef::Variable::My:
    file: lib/Sidef/Variable/My.pm
  Sidef::Variable::Ref:
    file: lib/Sidef/Variable/Ref.pm
  Sidef::Variable::Struct:
    file: lib/Sidef/Variable/Struct.pm
  Sidef::Variable::Variable:
    file: lib/Sidef/Variable/Variable.pm
  UNIVERSAL:
    file: lib/Sidef.pm
requires:
  Cwd: '0'
  Encode: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  Getopt::Std: '0'
  List::Util: '0'
  Math::BigFloat: '0'
  Math::BigInt: '0'
  POSIX: '0'
  Term::ReadLine: '0'
  Time::HiRes: '0'
  perl: v5.14.0
  utf8: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.03'
