
=encoding utf8

=head1 NAME

Sidef::Types::Bool::Bool

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Bool.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object
	* Sidef::Convert::Convert

=head1 METHODS


=head2 &

I<Obj> B<&> I<Obj> -> I<Obj>

Return the

=cut

=head2 dump

Bool.dump() -> I<Obj>

Return the

=cut

=head2 false

Bool.false() -> I<Obj>

Return the

=cut

=head2 is_true

Bool.is_true() -> I<Obj>

Return the

Aliases: I<isTrue>

=cut

=head2 new

Bool.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 not

Bool.not() -> I<Obj>

Return the

Aliases: I<flip>, I<toggle>, I<is_false>, I<isFalse>

=cut

=head2 to_bool

Bool.to_bool() -> I<Obj>

Return the

=cut

=head2 true

Bool.true() -> I<Obj>

Return the

=cut

=head2 |

I<Obj> B<|> I<Obj> -> I<Obj>

Return the

=cut
