
=encoding utf8

=head1 NAME

Sidef::Types::Bool::If

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = If.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Block::Do

=head1 METHODS


=head2 else

If.else() -> I<Obj>

Return the

=cut

=head2 if

If.if() -> I<Obj>

Return the

Aliases: I<call>, I<elsif>

=cut
