
=encoding utf8

=head1 NAME

Sidef::Types::Byte::Byte

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Byte.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Number::Number

=head1 METHODS


=head2 dump

Byte.dump() -> I<Obj>

Return the

=cut

=head2 new

Byte.new() -> I<Obj>

Return the

Aliases: I<call>

=cut
