
=encoding utf8

=head1 NAME

Sidef::Types::Byte::Bytes

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Bytes.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Array::Array

=head1 METHODS


=head2 call

Bytes.call() -> I<Obj>

Return the

=cut

=head2 dump

Bytes.dump() -> I<Obj>

Return the

=cut

=head2 encode

Bytes.encode() -> I<Obj>

Return the

=cut

=head2 join

Bytes.join() -> I<Obj>

Return the

=cut

=head2 new

Bytes.new() -> I<Obj>

Return the

=cut
