
=encoding utf8

=head1 NAME

Sidef::Object::Convert

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Convert(...)

=head1 METHODS

=head2 to_a

    self.to_a

Returns the

Aliases: I<to_array>

=cut

=head2 to_b

    self.to_b

Returns the

Aliases: I<to_bool>

=cut

=head2 to_bag

    self.to_bag

Returns the

=cut

=head2 to_caller

    self.to_caller

Returns the

=cut

=head2 to_dir

    self.to_dir

Returns the

=cut

=head2 to_f

    self.to_f

Returns the

Aliases: I<to_float>

=cut

=head2 to_fcaller

    self.to_fcaller

Returns the

=cut

=head2 to_file

    self.to_file

Returns the

=cut

=head2 to_i

    self.to_i

Returns the

Aliases: I<to_int>

=cut

=head2 to_m

    self.to_m

Returns the

Aliases: I<to_matrix>

=cut

=head2 to_n

    self.to_n

Returns the

Aliases: I<to_num>

=cut

=head2 to_r

    self.to_r

Returns the

Aliases: I<to_rat>

=cut

=head2 to_re

    self.to_re

Returns the

Aliases: I<to_regex>

=cut

=head2 to_s

    self.to_s

Returns the

Aliases: I<to_str>

=cut

=head2 to_set

    self.to_set

Returns the

=cut

=head2 to_type

    self.to_type(obj)

Returns the

=cut

=head2 to_v

    self.to_v

Returns the

Aliases: I<to_vector>

=cut
