=encoding utf8

=head1 NAME

Sidef::Object::Enumerator

=head1 DESCRIPTION

This class implements an enumerator object, allowing for functional-style operations such as mapping, filtering, and accessing elements within a collection. The enumerator is designed with extra parentheses to accommodate the absence of operator precedence rules in Sidef.

=head1 SYNOPSIS

var obj = Enumerator(...)

=head1 METHODS

=head2 count

    self.count(block)

Counts the elements in the enumerator collection that satisfy the given block condition. Returns the count.

Aliases: I<count_by>

=cut

=head2 each

    self.each(block)

Iterates over all elements in the enumerator, yielding each element to the given block. Returns the enumerator itself.

=cut

=head2 first

    self.first(n, block)

Returns the first `n` elements of the enumerator. If a block is provided, it retrieves the first `n` elements that satisfy the block condition.

=cut

=head2 grep

    self.grep(block)

Filters the elements in the enumerator collection based on the given block condition. Returns a new array with elements that satisfy the condition.

Aliases: I<select>

=cut

=head2 len

    self.len

Returns the total number of elements in the enumerator.

Aliases: I<size>, I<length>

=cut

=head2 map

    self.map(block)

Applies the given block to each element of the enumerator and returns a new array with the transformed elements.

Aliases: I<collect>

=cut

=head2 new

    self.new

Creates a new enumerator instance. Returns the new instance.

Aliases: I<call>

=cut

=head2 nth

    e.nth(n)
    e.nth(n, {...})

Retrieves the `n`-th term from the enumerator collection. An optional block can be given to filter out terms, counting only the terms for which the block returns a true value.

=cut

=head2 to_a

    self.to_a

Converts the enumerator into an array and returns it.

=cut

=head2 while

    self.while(block)

Yields elements to the given block and stops iterating when the block returns false. Returns an enumerator with the processed elements.

=cut
