
=encoding utf8

=head1 NAME

Sidef::Object::Lazy

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Lazy(...)

=head1 METHODS

=head2 each

    self.each(block)

Returns the

=cut

=head2 first

    self.first(n)

Returns the

=cut

=head2 first_by

    self.first_by(block)

Returns the

=cut

=head2 grep

    self.grep(block)

Returns the

Aliases: I<select>

=cut

=head2 iter

    self.iter

Returns the

=cut

=head2 lazy

    self.lazy

Returns the

=cut

=head2 map

    self.map(block)

Returns the

Aliases: I<collect>

=cut

=head2 new

    self.new

Returns the

=cut

=head2 nth

    self.nth(n)

Returns the

=cut

=head2 prod

    self.prod(block)

Returns the

Aliases: I<prod_by>

=cut

=head2 prod_kv

    self.prod_kv(block)

Returns the

=cut

=head2 reduce

    self.reduce(operator, result)

Returns the

=cut

=head2 reduce_by

    self.reduce_by(block, result)

Returns the

=cut

=head2 sum

    self.sum(block)

Returns the

Aliases: I<sum_by>

=cut

=head2 sum_kv

    self.sum_kv(block)

Returns the

=cut

=head2 to_a

    self.to_a

Returns the

=cut

=head2 while

    self.while(block)

Returns the

=cut
