
=encoding utf8

=head1 NAME

Sidef::Time::Gmtime

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Gmtime(...)


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 day

Gmtime.day() -> I<Obj>

Return the

Aliases: I<mday>, I<month_day>

=cut

=head2 hour

Gmtime.hour() -> I<Obj>

Return the

=cut

=head2 min

Gmtime.min() -> I<Obj>

Return the

Aliases: I<minute>

=cut

=head2 mon

Gmtime.mon() -> I<Obj>

Return the

Aliases: I<month>

=cut

=head2 sec

Gmtime.sec() -> I<Obj>

Return the

Aliases: I<second>

=cut

=head2 strf

Gmtime.strf() -> I<Obj>

Return the

Aliases: I<format>, I<strftime>

=cut

=head2 to_s

Gmtime.to_s() -> I<Obj>

Return the

Aliases: I<ctime>, I<to_str>

=cut

=head2 wday

Gmtime.wday() -> I<Obj>

Return the

Aliases: I<week_day>

=cut

=head2 yday

Gmtime.yday() -> I<Obj>

Return the

Aliases: I<year_day>

=cut

=head2 year

Gmtime.year() -> I<Obj>

Return the

=cut
