
=encoding utf8

=head1 NAME

Sidef::Time::Localtime

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Localtime.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Time::Gmtime

=head1 METHODS


=head2 ctime

Localtime.ctime() -> I<Obj>

Return the

=cut

=head2 day

Localtime.day() -> I<Obj>

Return the

Aliases: I<mday>, I<month_day>

=cut

=head2 hour

Localtime.hour() -> I<Obj>

Return the

=cut

=head2 isdst

Localtime.isdst() -> I<Obj>

Return the

=cut

=head2 min

Localtime.min() -> I<Obj>

Return the

Aliases: I<minute>

=cut

=head2 mon

Localtime.mon() -> I<Obj>

Return the

Aliases: I<month>

=cut

=head2 sec

Localtime.sec() -> I<Obj>

Return the

Aliases: I<second>

=cut

=head2 wday

Localtime.wday() -> I<Obj>

Return the

Aliases: I<week_day>

=cut

=head2 yday

Localtime.yday() -> I<Obj>

Return the

Aliases: I<year_day>

=cut

=head2 year

Localtime.year() -> I<Obj>

Return the

=cut
