
=encoding utf8

=head1 NAME

Sidef::Time::Time

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Time(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 dump

    self.dump

Returns the

=cut

=head2 gmt

    self.gmt

Returns the

Aliases: I<gmtime>

=cut

=head2 local

    self.local

Returns the

Aliases: I<localtime>

=cut

=head2 micro

    self.micro

Returns the

Aliases: I<micro_sec>, I<micro_seconds>

=cut

=head2 new

    self.new

Returns the

Aliases: I<call>

=cut

=head2 now

    self.now

Returns the

=cut

=head2 sec

    self.sec

Returns the

Aliases: I<time>

=cut

=head2 to_s

    self.to_s

Returns the

Aliases: I<to_str>

=cut
