
=encoding utf8

=head1 NAME

Sidef::Convert::Convert

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Convert.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef

=head1 METHODS

=head2 toArray

Convert.toArray() -> I<Bool>

Return the

=cut

=head2 toBool

Convert.toBool() -> I<Bool>

Return the

=cut

=head2 toByte

Convert.toByte() -> I<Bool>

Return the

=cut

=head2 toBytes

Convert.toBytes() -> I<Bool>

Return the

=cut

=head2 toChar

Convert.toChar() -> I<Bool>

Return the

=cut

=head2 toChars

Convert.toChars() -> I<Bool>

Return the

=cut

=head2 toDir

Convert.toDir() -> I<Bool>

Return the

=cut

=head2 toFile

Convert.toFile() -> I<Bool>

Return the

=cut

=head2 toInt

Convert.toInt() -> I<Bool>

Return the

=cut

=head2 toInteger

Convert.toInteger() -> I<Bool>

Return the

=cut

=head2 toString

Convert.toString() -> I<Bool>

Return the

=cut


=head2 to_array

Convert.to_array() -> I<Bool>

Return the

=cut

=head2 to_bool

Convert.to_bool() -> I<Bool>

Return the

=cut

=head2 to_byte

Convert.to_byte() -> I<Bool>

Return the

=cut

=head2 to_bytes

Convert.to_bytes() -> I<Bool>

Return the

=cut

=head2 to_char

Convert.to_char() -> I<Bool>

Return the

=cut

=head2 to_chars

Convert.to_chars() -> I<Bool>

Return the

=cut

=head2 to_dir

Convert.to_dir() -> I<Bool>

Return the

=cut

=head2 to_file

Convert.to_file() -> I<Bool>

Return the

=cut

=head2 to_i

Convert.to_i() -> I<Bool>

Return the

=cut

=head2 to_int

Convert.to_int() -> I<Bool>

Return the

=cut

=head2 to_integer

Convert.to_integer() -> I<Bool>

Return the

=cut

=head2 to_s

Convert.to_s() -> I<Bool>

Return the

=cut

=head2 to_string

Convert.to_string() -> I<Bool>

Return the

=cut
