
=encoding utf8

=head1 NAME

Sidef::Variable::ClassInit

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = ClassInit.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 <

I<Obj> B<E<lt>> I<Obj> -> I<Obj>

Return the

Aliases: I<+=()>, I<E<lt>E<lt>>, I<inherit>

=cut

=head2 =

I<Obj> B<=> I<Obj> -> I<Obj>

Return the

Aliases: I<replace>

=cut

=head2 alias

ClassInit.alias() -> I<Obj>

Return the

=cut

=head2 def_method

ClassInit.def_method() -> I<Obj>

Return the

=cut

=head2 def_var

ClassInit.def_var() -> I<Obj>

Return the

=cut

=head2 dump

ClassInit.dump() -> I<Obj>

Return the

=cut

=head2 invoke

ClassInit.invoke() -> I<Obj>

Return the

=cut

=head2 is_a

ClassInit.is_a() -> I<Obj>

Return the

Aliases: I<is_an>

=cut

=head2 method

ClassInit.method() -> I<Obj>

Return the

=cut

=head2 new

ClassInit.new() -> I<Obj>

Return the

Aliases: I<call>, I<init>, I<bcall>

=cut

=head2 respond_to

ClassInit.respond_to() -> I<Obj>

Return the

=cut
