
=encoding utf8

=head1 NAME

Sidef::Variable::Class

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Class.new(...);

=head1 METHODS


=head2 def_method

Class.def_method() -> I<Obj>

Return the

=cut

=head2 dump

Class.dump() -> I<Obj>

Return the

=cut

=head2 has_method

Class.has_method() -> I<Obj>

Return the

=cut

=head2 is_a

Class.is_a() -> I<Obj>

Return the

Aliases: I<is_an>

=cut
