
=encoding utf8

=head1 NAME

Sidef::Variable::Ref

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Ref.new(...));

=head1 METHODS

=head2 &

I<Num> B<&> I<Num> -> I<Num>

Return the

=cut


=head2 *

I<Num> B<*> I<Num> -> I<Num>

Return the

=cut

=head2 \

I<Num> B<\> I<Num> -> I<Num>

Return the

=cut
