
=encoding utf8

=head1 NAME

Sidef::Variable::Variable

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Variable.new(...);

=head1 METHODS


=head2 %=

I<Obj> B<%=> I<Obj> -> I<Obj>

Return the

=cut

=head2 &&=

I<Obj> B<&&=> I<Obj> -> I<Obj>

Return the

=cut

=head2 &=

I<Obj> B<&=> I<Obj> -> I<Obj>

Return the

=cut

=head2 **=

I<Obj> B<**=> I<Obj> -> I<Obj>

Return the

=cut

=head2 *=

I<Obj> B<*=> I<Obj> -> I<Obj>

Return the

=cut

=head2 ++

I<Obj> B<++> I<Obj> -> I<Obj>

Return the

=cut

=head2 +=

I<Obj> B<+=> I<Obj> -> I<Obj>

Return the

=cut

=head2 --

I<Obj> B<--> I<Obj> -> I<Obj>

Return the

=cut

=head2 -=

I<Obj> B<-=> I<Obj> -> I<Obj>

Return the

=cut

=head2 /=

I<Obj> B</=> I<Obj> -> I<Obj>

Return the

=cut

=head2 :=

I<Obj> B<:=> I<Obj> -> I<Obj>

Return the

=cut

=head2 <<=

I<Obj> B<E<lt>E<lt>=> I<Obj> -> I<Obj>

Return the

=cut

=head2 =

I<Obj> B<=> I<Obj> -> I<Obj>

Return the

=cut

=head2 >>=

I<Obj> B<E<gt>E<gt>=> I<Obj> -> I<Obj>

Return the

=cut

=head2 \\

I<Obj> B<\\> I<Obj> -> I<Obj>

Return the

=cut

=head2 \\=

I<Obj> B<\\=> I<Obj> -> I<Obj>

Return the

=cut

=head2 ^=

I<Obj> B<^=> I<Obj> -> I<Obj>

Return the

=cut

=head2 defined

Variable.defined() -> I<Obj>

Return the

=cut

=head2 |=

I<Obj> B<|=> I<Obj> -> I<Obj>

Return the

=cut

=head2 ||=

I<Obj> B<||=> I<Obj> -> I<Obj>

Return the

=cut

=head2 ÷=

I<Obj> B<÷=> I<Obj> -> I<Obj>

Return the

=cut
