
=encoding utf8

=head1 NAME

Sidef::Types::Glob::Dir

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Dir.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef::Convert::Convert

=head1 METHODS

=head2 +

I<Num> B<+> I<Num> -> I<Num>

Return the

=cut

=head2 absName

Dir.absName() -> I<Bool>

Return the

=cut


=head2 abs_name

Dir.abs_name() -> I<Bool>

Return the

=cut

=head2 absPath

Dir.absPath() -> I<Bool>

Return the

=cut

=head2 abs_path

Dir.abs_path() -> I<Bool>

Return the

=cut

=head2 chdir

Dir.chdir() -> I<Bool>

Return the

=cut

=head2 chroot

Dir.chroot() -> I<Bool>

Return the

=cut

=head2 concat

Dir.concat() -> I<Bool>

Return the

=cut

=head2 create

Dir.create() -> I<Bool>

Return the

=cut

=head2 createTree

Dir.createTree() -> I<Bool>

Return the

=cut

=head2 create_tree

Dir.create_tree() -> I<Bool>

Return the

=cut

=head2 dump

Dir.dump() -> I<Bool>

Return the

=cut

=head2 exists

Dir.exists() -> I<Bool>

Return the

=cut

=head2 get_value

Dir.get_value() -> I<Bool>

Return the

=cut

=head2 home

Dir.home() -> I<Bool>

Return the

=cut

=head2 isDir

Dir.isDir() -> I<Bool>

Return the

=cut

=head2 is_dir

Dir.is_dir() -> I<Bool>

Return the

=cut

=head2 isDirectory

Dir.isDirectory() -> I<Bool>

Return the

=cut

=head2 is_directory

Dir.is_directory() -> I<Bool>

Return the

=cut

=head2 isEmpty

Dir.isEmpty() -> I<Bool>

Return the

=cut

=head2 is_empty

Dir.is_empty() -> I<Bool>

Return the

=cut

=head2 lstat

Dir.lstat() -> I<Bool>

Return the

=cut

=head2 make

Dir.make() -> I<Bool>

Return the

=cut

=head2 makeTree

Dir.makeTree() -> I<Bool>

Return the

=cut

=head2 make_tree

Dir.make_tree() -> I<Bool>

Return the

=cut

=head2 new

Dir.new() -> I<Bool>

Return the

=cut

=head2 open

Dir.open() -> I<Bool>

Return the

=cut

=head2 parent

Dir.parent() -> I<Bool>

Return the

=cut

=head2 readLink

Dir.readLink() -> I<Bool>

Return the

=cut

=head2 readlink

Dir.readlink() -> I<Bool>

Return the

=cut

=head2 remove

Dir.remove() -> I<Bool>

Return the

=cut

=head2 removeTree

Dir.removeTree() -> I<Bool>

Return the

=cut

=head2 remove_tree

Dir.remove_tree() -> I<Bool>

Return the

=cut

=head2 split

Dir.split() -> I<Bool>

Return the

=cut

=head2 stat

Dir.stat() -> I<Bool>

Return the

=cut

=head2 utime

Dir.utime() -> I<Bool>

Return the

=cut
