
=encoding utf8

=head1 NAME

Sidef::Types::Glob::File

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = File(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::String::String

=head1 METHODS

=head2 abs

    File.abs()

Return the

Aliases: I<abs_name>, I<absname>, I<rel2abs>

=cut

=head2 abs_path

    File.abs_path()

Return the

Aliases: I<realpath>

=cut

=head2 access_time_days_diff

    File.access_time_days_diff()

Return the

=cut

=head2 append

    File.append()

Return the

=cut

=head2 base

    File.base()

Return the

Aliases: I<base_name>, I<basename>

=cut

=head2 change_time_days_diff

    File.change_time_days_diff()

Return the

=cut

=head2 chmod

    File.chmod()

Return the

=cut

=head2 chown

    File.chown()

Return the

=cut

=head2 compare

    File.compare()

Return the

=cut

=head2 cp

    File.cp()

Return the

Aliases: I<copy>

=cut

=head2 delete

    File.delete()

Return the

Aliases: I<remove>

=cut

=head2 dir

    File.dir()

Return the

Aliases: I<dir_name>, I<dirname>

=cut

=head2 dump

    File.dump()

Return the

=cut

=head2 edit

    File.edit()

Return the

=cut

=head2 exists

    File.exists()

Return the

=cut

=head2 has_setgid_bit

    File.has_setgid_bit()

Return the

=cut

=head2 has_setuid_bit

    File.has_setuid_bit()

Return the

=cut

=head2 has_sticky_bit

    File.has_sticky_bit()

Return the

=cut

=head2 is_abs

    File.is_abs()

Return the

Aliases: I<is_absolute>

=cut

=head2 is_binary

    File.is_binary()

Return the

=cut

=head2 is_block

    File.is_block()

Return the

=cut

=head2 is_char_device

    File.is_char_device()

Return the

=cut

=head2 is_dir

    File.is_dir()

Return the

Aliases: I<is_directory>

=cut

=head2 is_empty

    File.is_empty()

Return the

=cut

=head2 is_executable

    File.is_executable()

Return the

=cut

=head2 is_file

    File.is_file()

Return the

=cut

=head2 is_link

    File.is_link()

Return the

=cut

=head2 is_owned

    File.is_owned()

Return the

=cut

=head2 is_readable

    File.is_readable()

Return the

=cut

=head2 is_real_executable

    File.is_real_executable()

Return the

=cut

=head2 is_real_owned

    File.is_real_owned()

Return the

=cut

=head2 is_real_readable

    File.is_real_readable()

Return the

=cut

=head2 is_real_writeable

    File.is_real_writeable()

Return the

=cut

=head2 is_socket

    File.is_socket()

Return the

=cut

=head2 is_text

    File.is_text()

Return the

=cut

=head2 is_writeable

    File.is_writeable()

Return the

=cut

=head2 lstat

    File.lstat()

Return the

=cut

=head2 make

    File.make()

Return the

Aliases: I<touch>, I<create>, I<mkfile>

=cut

=head2 md5

    File.md5()

Return the

=cut

=head2 modification_time_days_diff

    File.modification_time_days_diff()

Return the

=cut

=head2 mv

    File.mv()

Return the

Aliases: I<move>

=cut

=head2 name

    File.name()

Return the

=cut

=head2 new

    File.new()

Return the

Aliases: I<call>

=cut

=head2 open

    File.open()

Return the

=cut

=head2 open_a

    File.open_a()

Return the

Aliases: I<open_append>

=cut

=head2 opendir

    File.opendir()

Return the

=cut

=head2 open_r

    File.open_r()

Return the

Aliases: I<open_read>

=cut

=head2 open_rw

    File.open_rw()

Return the

Aliases: I<open_read_write>

=cut

=head2 open_w

    File.open_w()

Return the

Aliases: I<open_write>

=cut

=head2 read

    File.read()

Return the

=cut

=head2 read_link

    File.read_link()

Return the

Aliases: I<readlink>

=cut

=head2 rel

    File.rel()

Return the

Aliases: I<abs2rel>, I<rel_name>, I<relname>

=cut

=head2 rename

    File.rename()

Return the

=cut

=head2 sha1

    File.sha1()

Return the

=cut

=head2 sha256

    File.sha256()

Return the

=cut

=head2 sha512

    File.sha512()

Return the

=cut

=head2 size

    File.size()

Return the

=cut

=head2 split

    File.split()

Return the

=cut

=head2 splitpath

    File.splitpath()

Return the

=cut

=head2 stat

    File.stat()

Return the

=cut

=head2 sysopen

    File.sysopen()

Return the

=cut

=head2 to_file

    File.to_file()

Return the

=cut

=head2 to_s

    File.to_s()

Return the

Aliases: I<to_str>

=cut

=head2 truncate

    File.truncate()

Return the

=cut

=head2 unlink

    File.unlink()

Return the

=cut

=head2 utime

    File.utime()

Return the

=cut

=head2 write

    File.write()

Return the

=cut
