
=encoding utf8

=head1 NAME

Sidef::Types::Glob::FileHandle

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (FileHandle.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef

=head1 METHODS


=head2 close

FileHandle.close() -> I<Bool>

Return the

=cut

=head2 each

FileHandle.each() -> I<Bool>

Return the

=cut

=head2 eof

FileHandle.eof() -> I<Bool>

Return the

=cut

=head2 file

FileHandle.file() -> I<Bool>

Return the

=cut

=head2 fileno

FileHandle.fileno() -> I<Bool>

Return the

=cut

=head2 flock

FileHandle.flock() -> I<Bool>

Return the

=cut

=head2 get_lines

FileHandle.get_lines() -> I<Bool>

Return the

=cut

=head2 getLines

FileHandle.getLines() -> I<Bool>

Return the

=cut

=head2 getlines

FileHandle.getlines() -> I<Bool>

Return the

=cut

=head2 input_separator

FileHandle.input_separator() -> I<Bool>

Return the

=cut

=head2 inputSeparator

FileHandle.inputSeparator() -> I<Bool>

Return the

=cut

=head2 is_on_tty

FileHandle.is_on_tty() -> I<Bool>

Return the

=cut

=head2 isOnTty

FileHandle.isOnTty() -> I<Bool>

Return the

=cut

=head2 lines

FileHandle.lines() -> I<Bool>

Return the

=cut

=head2 lock

FileHandle.lock() -> I<Bool>

Return the

=cut

=head2 lstat

FileHandle.lstat() -> I<Bool>

Return the

=cut

=head2 parent

FileHandle.parent() -> I<Bool>

Return the

=cut

=head2 print

FileHandle.print() -> I<Bool>

Return the

=cut

=head2 println

FileHandle.println() -> I<Bool>

Return the

=cut

=head2 read

FileHandle.read() -> I<Bool>

Return the

=cut

=head2 read_all

FileHandle.read_all() -> I<Bool>

Return the

=cut

=head2 read_char

FileHandle.read_char() -> I<Bool>

Return the

=cut

=head2 readAll

FileHandle.readAll() -> I<Bool>

Return the

=cut

=head2 readall

FileHandle.readall() -> I<Bool>

Return the

=cut

=head2 readChar

FileHandle.readChar() -> I<Bool>

Return the

=cut

=head2 readLine

FileHandle.readLine() -> I<Bool>

Return the

=cut

=head2 readline

FileHandle.readline() -> I<Bool>

Return the

=cut

=head2 readLines

FileHandle.readLines() -> I<Bool>

Return the

=cut

=head2 readlines

FileHandle.readlines() -> I<Bool>

Return the

=cut

=head2 readln

FileHandle.readln() -> I<Bool>

Return the

=cut

=head2 seek

FileHandle.seek() -> I<Bool>

Return the

=cut

=head2 sep

FileHandle.sep() -> I<Bool>

Return the

=cut

=head2 separator

FileHandle.separator() -> I<Bool>

Return the

=cut

=head2 stat

FileHandle.stat() -> I<Bool>

Return the

=cut

=head2 stderr

FileHandle.stderr() -> I<Bool>

Return the

=cut

=head2 stdin

FileHandle.stdin() -> I<Bool>

Return the

=cut

=head2 stdout

FileHandle.stdout() -> I<Bool>

Return the

=cut

=head2 sysRead

FileHandle.sysRead() -> I<Bool>

Return the

=cut

=head2 sysread

FileHandle.sysread() -> I<Bool>

Return the

=cut

=head2 sysSeek

FileHandle.sysSeek() -> I<Bool>

Return the

=cut

=head2 sysseek

FileHandle.sysseek() -> I<Bool>

Return the

=cut

=head2 tell

FileHandle.tell() -> I<Bool>

Return the

=cut

=head2 truncate

FileHandle.truncate() -> I<Bool>

Return the

=cut

=head2 unlock

FileHandle.unlock() -> I<Bool>

Return the

=cut

=head2 write_string

FileHandle.write_string() -> I<Bool>

Return the

=cut

=head2 writeString

FileHandle.writeString() -> I<Bool>

Return the

=cut
