
=encoding utf8

=head1 NAME

Sidef::Types::Glob::PipeHandle

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (PipeHandle.new(...));

=head1 METHODS


=head2 close

PipeHandle.close() -> I<Bool>

Return the

=cut

=head2 get_lines

PipeHandle.get_lines() -> I<Bool>

Return the

=cut

=head2 getLines

PipeHandle.getLines() -> I<Bool>

Return the

=cut

=head2 parent

PipeHandle.parent() -> I<Bool>

Return the

=cut

=head2 pipe

PipeHandle.pipe() -> I<Bool>

Return the

=cut

=head2 read

PipeHandle.read() -> I<Bool>

Return the

=cut

=head2 read_all

PipeHandle.read_all() -> I<Bool>

Return the

=cut

=head2 readAll

PipeHandle.readAll() -> I<Bool>

Return the

=cut

=head2 readline

PipeHandle.readline() -> I<Bool>

Return the

=cut

=head2 readLine

PipeHandle.readLine() -> I<Bool>

Return the

=cut
