
=encoding utf8

=head1 NAME

Sidef::Types::Glob::Pipe

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Pipe(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 command

    Pipe.command()

Returns the

=cut

=head2 new

    Pipe.new()

Returns the

Aliases: I<call>

=cut

=head2 open

    Pipe.open()

Returns the

=cut

=head2 open_r

    Pipe.open_r()

Returns the

Aliases: I<open_read>

=cut

=head2 open_w

    Pipe.open_w()

Returns the

Aliases: I<open_write>

=cut

=head2 to_s

    Pipe.to_s()

Returns the

Aliases: I<dump>, I<to_str>

=cut
