
=encoding utf8

=head1 NAME

Sidef::Types::Glob::Socket

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Socket(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 getaddrinfo

    self.getaddrinfo

Returns the

=cut

=head2 gethostbyaddr

    self.gethostbyaddr(addr, addrtype)

Returns the

=cut

=head2 gethostbyname

    self.gethostbyname(name)

Returns the

=cut

=head2 gethostent

    self.gethostent

Returns the

=cut

=head2 getnameinfo

    self.getnameinfo

Returns the

=cut

=head2 getnetbyaddr

    self.getnetbyaddr(addr, addrtype)

Returns the

=cut

=head2 getnetbyname

    self.getnetbyname(name)

Returns the

=cut

=head2 getnetent

    self.getnetent

Returns the

=cut

=head2 getprotobyname

    self.getprotobyname(name)

Returns the

=cut

=head2 getprotobynumber

    self.getprotobynumber(num)

Returns the

=cut

=head2 getprotoent

    self.getprotoent

Returns the

=cut

=head2 getservbyname

    self.getservbyname(name, proto)

Returns the

=cut

=head2 getservbyport

    self.getservbyport(port, proto)

Returns the

=cut

=head2 getservent

    self.getservent

Returns the

=cut

=head2 inet_aton

    self.inet_aton

Returns the

=cut

=head2 inet_ntoa

    self.inet_ntoa

Returns the

=cut

=head2 inet_ntop

    self.inet_ntop

Returns the

=cut

=head2 inet_pton

    self.inet_pton

Returns the

=cut

=head2 new

    self.new

Returns the

=cut

=head2 open

    self.open(domain, type, protocol)

Returns the

=cut

=head2 pack_ip_mreq

    self.pack_ip_mreq

Returns the

=cut

=head2 pack_ip_mreq_source

    self.pack_ip_mreq_source

Returns the

=cut

=head2 pack_ipv6_mreq

    self.pack_ipv6_mreq

Returns the

=cut

=head2 pack_sockaddr_in

    self.pack_sockaddr_in

Returns the

=cut

=head2 pack_sockaddr_in6

    self.pack_sockaddr_in6

Returns the

=cut

=head2 pack_sockaddr_un

    self.pack_sockaddr_un

Returns the

=cut

=head2 sethostent

    self.sethostent(stayopen)

Returns the

=cut

=head2 setnetent

    self.setnetent(stayopen)

Returns the

=cut

=head2 setprotoent

    self.setprotoent(stayopen)

Returns the

=cut

=head2 setservent

    self.setservent(stayopen)

Returns the

=cut

=head2 sockaddr_family

    self.sockaddr_family

Returns the

=cut

=head2 sockaddr_in

    self.sockaddr_in

Returns the

=cut

=head2 sockaddr_in6

    self.sockaddr_in6

Returns the

=cut

=head2 sockaddr_un

    self.sockaddr_un

Returns the

=cut

=head2 socketpair

    self.socketpair(socket1, socket2, domain, type, protocol)

Returns the

=cut

=head2 unpack_ip_mreq

    self.unpack_ip_mreq

Returns the

=cut

=head2 unpack_ip_mreq_source

    self.unpack_ip_mreq_source

Returns the

=cut

=head2 unpack_ipv6_mreq

    self.unpack_ipv6_mreq

Returns the

=cut

=head2 unpack_sockaddr_in

    self.unpack_sockaddr_in

Returns the

=cut

=head2 unpack_sockaddr_in6

    self.unpack_sockaddr_in6

Returns the

=cut

=head2 unpack_sockaddr_un

    self.unpack_sockaddr_un

Returns the

=cut
