
=encoding utf8

=head1 NAME

Sidef::Types::Glob::Socket

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Socket.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 getaddrinfo

Socket.getaddrinfo() -> I<Obj>

Return the

=cut

=head2 gethostbyaddr

Socket.gethostbyaddr() -> I<Obj>

Return the

=cut

=head2 gethostbyname

Socket.gethostbyname() -> I<Obj>

Return the

=cut

=head2 gethostent

Socket.gethostent() -> I<Obj>

Return the

=cut

=head2 getnameinfo

Socket.getnameinfo() -> I<Obj>

Return the

=cut

=head2 getnetbyaddr

Socket.getnetbyaddr() -> I<Obj>

Return the

=cut

=head2 getnetbyname

Socket.getnetbyname() -> I<Obj>

Return the

=cut

=head2 getnetent

Socket.getnetent() -> I<Obj>

Return the

=cut

=head2 getprotobyname

Socket.getprotobyname() -> I<Obj>

Return the

=cut

=head2 getprotobynumber

Socket.getprotobynumber() -> I<Obj>

Return the

=cut

=head2 getprotoent

Socket.getprotoent() -> I<Obj>

Return the

=cut

=head2 getservbyname

Socket.getservbyname() -> I<Obj>

Return the

=cut

=head2 getservbyport

Socket.getservbyport() -> I<Obj>

Return the

=cut

=head2 getservent

Socket.getservent() -> I<Obj>

Return the

=cut

=head2 inet_aton

Socket.inet_aton() -> I<Obj>

Return the

=cut

=head2 inet_ntoa

Socket.inet_ntoa() -> I<Obj>

Return the

=cut

=head2 inet_ntop

Socket.inet_ntop() -> I<Obj>

Return the

=cut

=head2 inet_pton

Socket.inet_pton() -> I<Obj>

Return the

=cut

=head2 new

Socket.new() -> I<Obj>

Return the

=cut

=head2 open

Socket.open() -> I<Obj>

Return the

=cut

=head2 pack_ip_mreq

Socket.pack_ip_mreq() -> I<Obj>

Return the

=cut

=head2 pack_ip_mreq_source

Socket.pack_ip_mreq_source() -> I<Obj>

Return the

=cut

=head2 pack_ipv6_mreq

Socket.pack_ipv6_mreq() -> I<Obj>

Return the

=cut

=head2 pack_sockaddr_in

Socket.pack_sockaddr_in() -> I<Obj>

Return the

=cut

=head2 pack_sockaddr_in6

Socket.pack_sockaddr_in6() -> I<Obj>

Return the

=cut

=head2 pack_sockaddr_un

Socket.pack_sockaddr_un() -> I<Obj>

Return the

=cut

=head2 sethostent

Socket.sethostent() -> I<Obj>

Return the

=cut

=head2 setnetent

Socket.setnetent() -> I<Obj>

Return the

=cut

=head2 setprotoent

Socket.setprotoent() -> I<Obj>

Return the

=cut

=head2 setservent

Socket.setservent() -> I<Obj>

Return the

=cut

=head2 sockaddr_family

Socket.sockaddr_family() -> I<Obj>

Return the

=cut

=head2 sockaddr_in

Socket.sockaddr_in() -> I<Obj>

Return the

=cut

=head2 sockaddr_in6

Socket.sockaddr_in6() -> I<Obj>

Return the

=cut

=head2 sockaddr_un

Socket.sockaddr_un() -> I<Obj>

Return the

=cut

=head2 socketpair

Socket.socketpair() -> I<Obj>

Return the

=cut

=head2 unpack_ip_mreq

Socket.unpack_ip_mreq() -> I<Obj>

Return the

=cut

=head2 unpack_ip_mreq_source

Socket.unpack_ip_mreq_source() -> I<Obj>

Return the

=cut

=head2 unpack_ipv6_mreq

Socket.unpack_ipv6_mreq() -> I<Obj>

Return the

=cut

=head2 unpack_sockaddr_in

Socket.unpack_sockaddr_in() -> I<Obj>

Return the

=cut

=head2 unpack_sockaddr_in6

Socket.unpack_sockaddr_in6() -> I<Obj>

Return the

=cut

=head2 unpack_sockaddr_un

Socket.unpack_sockaddr_un() -> I<Obj>

Return the

=cut
