
=encoding utf8

=head1 NAME

Sidef::Types::Glob::SocketHandle

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = SocketHandle(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Glob::FileHandle

=head1 METHODS

=head2 accept

    self.accept

Returns the

=cut

=head2 bind

    self.bind(name)

Returns the

=cut

=head2 connect

    self.connect(name)

Returns the

=cut

=head2 getpeername

    self.getpeername

Returns the

=cut

=head2 getsockname

    self.getsockname

Returns the

=cut

=head2 getsockopt

    self.getsockopt(level, optname)

Returns the

=cut

=head2 listen

    self.listen(queuesize)

Returns the

=cut

=head2 new

    self.new

Returns the

Aliases: I<call>

=cut

=head2 recv

    self.recv(length, flags)

Returns the

=cut

=head2 send

    self.send(msg, flags, to)

Returns the

=cut

=head2 setsockopt

    self.setsockopt(level, optname, optval)

Returns the

=cut

=head2 shutdown

    self.shutdown(how)

Returns the

=cut
