
=encoding utf8

=head1 NAME

Sidef::Types::Glob::Stat

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Stat(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 all

    Stat.all()

Returns the

=cut

=head2 atime

    Stat.atime()

Returns the

=cut

=head2 blksize

    Stat.blksize()

Returns the

=cut

=head2 blocks

    Stat.blocks()

Returns the

=cut

=head2 ctime

    Stat.ctime()

Returns the

=cut

=head2 dev

    Stat.dev()

Returns the

=cut

=head2 gid

    Stat.gid()

Returns the

=cut

=head2 ino

    Stat.ino()

Returns the

=cut

=head2 lstat

    Stat.lstat()

Returns the

=cut

=head2 mode

    Stat.mode()

Returns the

=cut

=head2 mtime

    Stat.mtime()

Returns the

=cut

=head2 nlink

    Stat.nlink()

Returns the

=cut

=head2 parent

    Stat.parent()

Returns the

=cut

=head2 rdev

    Stat.rdev()

Returns the

=cut

=head2 size

    Stat.size()

Returns the

=cut

=head2 stat

    Stat.stat()

Returns the

=cut

=head2 uid

    Stat.uid()

Returns the

=cut
