
=encoding utf8

=head1 NAME

Sidef::Types::Array::MultiArray

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = MultiArray.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 <<

I<Obj> B<E<lt>E<lt>> I<Obj> -> I<Obj>

Return the

Aliases: I<push>, I<append>

=cut

=head2 dump

MultiArray.dump() -> I<Obj>

Return the

=cut

=head2 each

MultiArray.each() -> I<Obj>

Return the

=cut

=head2 map

MultiArray.map() -> I<Obj>

Return the

=cut

=head2 new

MultiArray.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 to_a

MultiArray.to_a() -> I<Obj>

Return the

Aliases: I<to_array>

=cut
