
=encoding utf8

=head1 NAME

Sidef::Types::Array::RangeString

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = RangeString.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 bounds

RangeString.bounds() -> I<Obj>

Return the

=cut

=head2 contains

RangeString.contains() -> I<Obj>

Return the

Aliases: I<includes>

=cut

=head2 each

RangeString.each() -> I<Obj>

Return the

=cut

=head2 max

RangeString.max() -> I<Obj>

Return the

=cut

=head2 min

RangeString.min() -> I<Obj>

Return the

=cut

=head2 new

RangeString.new() -> I<Obj>

Return the

=cut

=head2 reverse

RangeString.reverse() -> I<Obj>

Return the

=cut

=head2 to_a

RangeString.to_a() -> I<Obj>

Return the

Aliases: I<to_array>

=cut
