
=encoding utf8

=head1 NAME

Sidef::Types::Array::Vector

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Vector(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Array::Array

=head1 METHODS

=head2 &

I<Obj> B<&> I<Obj> -> I<Obj>

Return the

Aliases: I<and>

=cut

=head2 *

I<Obj> B<*> I<Obj> -> I<Obj>

Return the

Aliases: I<mul>

=cut

=head2 +

I<Obj> B<+> I<Obj> -> I<Obj>

Return the

Aliases: I<add>

=cut

=head2 -

I<Obj> B<-> I<Obj> -> I<Obj>

Return the

Aliases: I<sub>

=cut

=head2 /

I<Obj> B</> I<Obj> -> I<Obj>

Return the

Aliases: I<÷>, I<div>

=cut

=head2 ^

I<Obj> B<^> I<Obj> -> I<Obj>

Return the

Aliases: I<xor>

=cut

=head2 abs

Vector.abs() -> I<Obj>

Return the

=cut

=head2 atan2

Vector.atan2() -> I<Obj>

Return the

=cut

=head2 ceil

Vector.ceil() -> I<Obj>

Return the

=cut

=head2 chebyshev_dist

Vector.chebyshev_dist() -> I<Obj>

Return the

=cut

=head2 dist

Vector.dist() -> I<Obj>

Return the

=cut

=head2 dist_norm

Vector.dist_norm() -> I<Obj>

Return the

=cut

=head2 floor

Vector.floor() -> I<Obj>

Return the

=cut

=head2 manhattan_dist

Vector.manhattan_dist() -> I<Obj>

Return the

=cut

=head2 manhattan_norm

Vector.manhattan_norm() -> I<Obj>

Return the

=cut

=head2 neg

Vector.neg() -> I<Obj>

Return the

=cut

=head2 new

Vector.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 norm

Vector.norm() -> I<Obj>

Return the

=cut

=head2 round

Vector.round() -> I<Obj>

Return the

=cut

=head2 to_a

Vector.to_a() -> I<Obj>

Return the

Aliases: I<to_array>

=cut

=head2 to_s

Vector.to_s() -> I<Obj>

Return the

Aliases: I<dump>, I<to_str>

=cut

=head2 zero

Vector.zero() -> I<Obj>

Return the

=cut

=head2 |

I<Obj> B<|> I<Obj> -> I<Obj>

Return the

Aliases: I<or>

=cut
