
=encoding utf8

=head1 NAME

Sidef

=head1 DESCRIPTION

This module provides some methods for static objects.

=head1 SYNOPSIS

This module can only be used as a parent:

        our @ISA = qw(Sidef);

or

        use parent qw(Sidef);

=head1 METHODS


=head2 !=

I<Obj> B<!=> I<Obj> -> I<Bool>

Return true if two objects are not of the same type.

    nil != 4     # True
    nil != nil   # False

=cut

=head2 ==

I<Obj> B<==> I<Obj> -> I<Bool>

Return true if two objects are of the same type.

    nil   == nil   # True
    false == nil   # False

=cut
