
=encoding utf8

=head1 NAME

Sidef - The Sidef Programming Language

=head1 DESCRIPTION

This in the main object which provides some SUPER methods.

=head1 SYNOPSIS

This module can only be used as a parent:

        our @ISA = qw(Sidef);

or

        use parent qw(Sidef);

=head1 METHODS


=head2 !=

I<Obj> B<!=> I<Obj> -> I<Bool>

Return true when two objects are not of the same type.

    nil != 4     # True
    nil != nil   # False

=cut

=head2 ==

I<Obj> B<==> I<Obj> -> I<Bool>

Return true when two objects are of the same type.

    nil   == nil   # True
    false == nil   # False

=cut

=head2 def_method

Obj.def_method(name, block) -> I<Obj>

Define a method for the self object.

=cut

=head2 is_a

Obj.is_a(Obj) -> I<Bool>

Returns true when both objects have the same type.

Aliases: I<is_an>

=cut

=head2 method

Obj.method(name; args...) -> I<LazyMethod>

Returns a lazy method call for the main object.

=cut

=head2 METHODS

Obj.METHODS() -> I<Hash>

Returns a new hash with the method names as keys and I<LazyMethod> objects as values for the self object.

=cut

=head2 respond_to

Obj.respond_to(method_name) -> I<Bool>

Returns true when the I<Obj> responds to a given method name.

Aliases: I<respondTo>

=cut

=head2 super_join

Obj.super_join(args...) -> I<Obj>

Returns a new I<Obj> with all the arguments concatenated together.

=cut
