
=encoding utf8

=head1 NAME

Sidef::Types::Range::RangeNumber

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = RangeNumber(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Range::Range
       * Sidef::Object::Object

=head1 METHODS

=head2 avg

RangeNumber.avg() -> I<Obj>

Return the

=cut

=head2 avg_by

RangeNumber.avg_by() -> I<Obj>

Return the

=cut

=head2 bsearch

RangeNumber.bsearch() -> I<Obj>

Return the

=cut

=head2 bsearch_ge

RangeNumber.bsearch_ge() -> I<Obj>

Return the

=cut

=head2 bsearch_le

RangeNumber.bsearch_le() -> I<Obj>

Return the

=cut

=head2 iter

RangeNumber.iter() -> I<Obj>

Return the

=cut

=head2 new

RangeNumber.new() -> I<Obj>

Return the

Aliases: I<call>

=cut

=head2 prod

RangeNumber.prod() -> I<Obj>

Return the

=cut

=head2 prod_by

RangeNumber.prod_by() -> I<Obj>

Return the

=cut

=head2 sum

RangeNumber.sum() -> I<Obj>

Return the

=cut

=head2 sum_by

RangeNumber.sum_by() -> I<Obj>

Return the

=cut

=head2 to_s

RangeNumber.to_s() -> I<Obj>

Return the

Aliases: I<dump>, I<to_str>

=cut
