
=encoding utf8

=head1 NAME

Sidef::Types::Range::RangeNumber

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = RangeNumber(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Range::Range
       * Sidef::Object::Object

=head1 METHODS

=head2 Π

    self.Π(arg)

Returns the

Aliases: I<prod>

=cut

=head2 Σ

    self.Σ(arg)

Returns the

Aliases: I<sum>

=cut

=head2 almost_prime_count

    self.almost_prime_count

Returns the

=cut

=head2 almost_primes

    self.almost_primes

Returns the

=cut

=head2 almost_prime_sum

    self.almost_prime_sum

Returns the

=cut

=head2 avg

    self.avg(arg)

Returns the

=cut

=head2 avg_by

    self.avg_by(block)

Returns the

=cut

=head2 bsearch

    self.bsearch(block)

Returns the

=cut

=head2 bsearch_ge

    self.bsearch_ge(block)

Returns the

=cut

=head2 bsearch_le

    self.bsearch_le(block)

Returns the

=cut

=head2 carmichael

    self.carmichael

Returns the

=cut

=head2 composite_count

    self.composite_count

Returns the

=cut

=head2 composites

    self.composites

Returns the

=cut

=head2 composite_sum

    self.composite_sum

Returns the

=cut

=head2 cubefree

    self.cubefree

Returns the

=cut

=head2 cubefree_count

    self.cubefree_count

Returns the

=cut

=head2 cubefree_sum

    self.cubefree_sum

Returns the

=cut

=head2 cubefull

    self.cubefull

Returns the

=cut

=head2 cubefull_count

    self.cubefull_count

Returns the

=cut

=head2 cubefull_sum

    self.cubefull_sum

Returns the

=cut

=head2 each_almost_prime

    self.each_almost_prime

Returns the

=cut

=head2 each_carmichael

    self.each_carmichael

Returns the

=cut

=head2 each_composite

    self.each_composite

Returns the

=cut

=head2 each_cubefree

    self.each_cubefree

Returns the

=cut

=head2 each_cubefull

    self.each_cubefull

Returns the

=cut

=head2 each_lucas_carmichael

    self.each_lucas_carmichael

Returns the

=cut

=head2 each_noncubefree

    self.each_noncubefree

Returns the

=cut

=head2 each_nonpowerfree

    self.each_nonpowerfree

Returns the

=cut

=head2 each_nonsquarefree

    self.each_nonsquarefree

Returns the

=cut

=head2 each_omega_prime

    self.each_omega_prime

Returns the

=cut

=head2 each_powerfree

    self.each_powerfree

Returns the

=cut

=head2 each_powerful

    self.each_powerful

Returns the

=cut

=head2 each_prime

    self.each_prime

Returns the

=cut

=head2 each_prime_power

    self.each_prime_power

Returns the

=cut

=head2 each_semiprime

    self.each_semiprime

Returns the

=cut

=head2 each_squarefree

    self.each_squarefree

Returns the

=cut

=head2 each_squarefree_almost_prime

    self.each_squarefree_almost_prime

Returns the

=cut

=head2 each_squarefree_semiprime

    self.each_squarefree_semiprime

Returns the

=cut

=head2 each_squarefull

    self.each_squarefull

Returns the

=cut

=head2 faulhaber

    self.faulhaber(k)

Returns the

Aliases: I<faulhaber_sum>

=cut

=head2 gcd

    self.gcd(arg)

Returns the

=cut

=head2 gcd_by

    self.gcd_by(block)

Returns the

=cut

=head2 iter

    self.iter

Returns the

=cut

=head2 lcm

    self.lcm(arg)

Returns the

=cut

=head2 lcm_by

    self.lcm_by(block)

Returns the

=cut

=head2 lucas_carmichael

    self.lucas_carmichael

Returns the

=cut

=head2 mertens

    self.mertens

Returns the

=cut

=head2 new

    self.new

Returns the

Aliases: I<call>

=cut

=head2 noncubefree

    self.noncubefree

Returns the

=cut

=head2 noncubefree_count

    self.noncubefree_count

Returns the

=cut

=head2 noncubefree_sum

    self.noncubefree_sum

Returns the

=cut

=head2 nonpowerfree

    self.nonpowerfree

Returns the

=cut

=head2 nonpowerfree_count

    self.nonpowerfree_count

Returns the

=cut

=head2 nonpowerfree_sum

    self.nonpowerfree_sum

Returns the

=cut

=head2 nonsquarefree

    self.nonsquarefree

Returns the

=cut

=head2 nonsquarefree_count

    self.nonsquarefree_count

Returns the

=cut

=head2 nonsquarefree_sum

    self.nonsquarefree_sum

Returns the

=cut

=head2 omega_prime_count

    self.omega_prime_count

Returns the

=cut

=head2 omega_primes

    self.omega_primes

Returns the

=cut

=head2 omega_prime_sum

    self.omega_prime_sum

Returns the

=cut

=head2 powerfree

    self.powerfree

Returns the

=cut

=head2 powerfree_count

    self.powerfree_count

Returns the

=cut

=head2 powerfree_sum

    self.powerfree_sum

Returns the

=cut

=head2 powerful

    self.powerful

Returns the

=cut

=head2 powerful_count

    self.powerful_count

Returns the

=cut

=head2 powerful_sum

    self.powerful_sum

Returns the

=cut

=head2 prime_count

    self.prime_count

Returns the

=cut

=head2 prime_power_count

    self.prime_power_count

Returns the

=cut

=head2 prime_powers

    self.prime_powers

Returns the

=cut

=head2 prime_power_sum

    self.prime_power_sum

Returns the

=cut

=head2 primes

    self.primes

Returns the

=cut

=head2 prime_sum

    self.prime_sum

Returns the

=cut

=head2 prod_by

    self.prod_by(block)

Returns the

=cut

=head2 rough_count

    self.rough_count

Returns the

=cut

=head2 semiprime_count

    self.semiprime_count

Returns the

=cut

=head2 semiprimes

    self.semiprimes

Returns the

=cut

=head2 semiprime_sum

    self.semiprime_sum

Returns the

=cut

=head2 smooth_count

    self.smooth_count

Returns the

=cut

=head2 squarefree

    self.squarefree

Returns the

=cut

=head2 squarefree_almost_prime_count

    self.squarefree_almost_prime_count

Returns the

=cut

=head2 squarefree_almost_primes

    self.squarefree_almost_primes

Returns the

=cut

=head2 squarefree_almost_prime_sum

    self.squarefree_almost_prime_sum

Returns the

=cut

=head2 squarefree_count

    self.squarefree_count

Returns the

=cut

=head2 squarefree_semiprime_count

    self.squarefree_semiprime_count

Returns the

=cut

=head2 squarefree_semiprimes

    self.squarefree_semiprimes

Returns the

=cut

=head2 squarefree_semiprime_sum

    self.squarefree_semiprime_sum

Returns the

=cut

=head2 squarefree_sum

    self.squarefree_sum

Returns the

=cut

=head2 squarefull

    self.squarefull

Returns the

=cut

=head2 squarefull_count

    self.squarefull_count

Returns the

=cut

=head2 squarefull_sum

    self.squarefull_sum

Returns the

=cut

=head2 sum_by

    self.sum_by(block)

Returns the

=cut

=head2 to_s

    self.to_s

Returns the

Aliases: I<dump>, I<to_str>

=cut
