
=encoding utf8

=head1 NAME

Sidef::Types::Range::RangeString

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = RangeString(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Types::Range::Range
       * Sidef::Object::Object

=head1 METHODS

=head2 call

    RangeString.call()

Return the

=cut

=head2 contain

    RangeString.contain()

Return the

Aliases: I<include>, I<contains>, I<includes>

=cut

=head2 from

    RangeString.from()

Return the

=cut

=head2 iter

    RangeString.iter()

Return the

=cut

=head2 max

    RangeString.max()

Return the

=cut

=head2 min

    RangeString.min()

Return the

=cut

=head2 new

    RangeString.new()

Return the

=cut

=head2 pick

    RangeString.pick()

Return the

=cut

=head2 rand

    RangeString.rand()

Return the

Aliases: I<sample>

=cut

=head2 to

    RangeString.to()

Return the

=cut

=head2 to_s

    RangeString.to_s()

Return the

Aliases: I<dump>, I<to_str>

=cut
