
=encoding utf8

=head1 NAME

Sidef::Types::Grapheme::Graphemes

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Graphemes.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Array::Array

=head1 METHODS


=head2 call

Graphemes.call() -> I<Obj>

Return the

=cut

=head2 dump

Graphemes.dump() -> I<Obj>

Return the

=cut

=head2 new

Graphemes.new() -> I<Obj>

Return the

=cut
