
=encoding utf8

=head1 NAME

Sidef::Types::Char::Char

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Char.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Convert::Convert
	* Sidef::Types::String::String

=head1 METHODS


=head2 call

Char.call() -> I<Obj>

Return the

=cut

=head2 dump

Char.dump() -> I<Obj>

Return the

=cut

=head2 new

Char.new() -> I<Obj>

Return the

=cut
