
=encoding utf8

=head1 NAME

Sidef::Types::Char::Char

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Char.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::String::String
	* Sidef::Convert::Convert

=head1 METHODS


=head2 new

Char.new() -> I<Bool>

Return the

=cut
