
=encoding utf8

=head1 NAME

Sidef::Types::Char::Chars

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Chars.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Array::Array
	* Sidef::Convert::Convert

=head1 METHODS


=head2 new

Chars.new() -> I<Bool>

Return the

=cut
