
=encoding utf8

=head1 NAME

Sidef::Math::Math

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Math.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 acos

Math.acos() -> I<Obj>

Return the

=cut

=head2 acosec

Math.acosec() -> I<Obj>

Return the

=cut

=head2 acosech

Math.acosech() -> I<Obj>

Return the

=cut

=head2 acosh

Math.acosh() -> I<Obj>

Return the

=cut

=head2 acot

Math.acot() -> I<Obj>

Return the

=cut

=head2 acotan

Math.acotan() -> I<Obj>

Return the

=cut

=head2 acotanh

Math.acotanh() -> I<Obj>

Return the

=cut

=head2 acoth

Math.acoth() -> I<Obj>

Return the

=cut

=head2 acsc

Math.acsc() -> I<Obj>

Return the

=cut

=head2 acsch

Math.acsch() -> I<Obj>

Return the

=cut

=head2 asec

Math.asec() -> I<Obj>

Return the

=cut

=head2 asech

Math.asech() -> I<Obj>

Return the

=cut

=head2 asin

Math.asin() -> I<Obj>

Return the

=cut

=head2 asinh

Math.asinh() -> I<Obj>

Return the

=cut

=head2 atan

Math.atan() -> I<Obj>

Return the

=cut

=head2 atan2

Math.atan2() -> I<Obj>

Return the

=cut

=head2 atanh

Math.atanh() -> I<Obj>

Return the

=cut

=head2 avg

Math.avg() -> I<Obj>

Return the

=cut

=head2 cosec

Math.cosec() -> I<Obj>

Return the

=cut

=head2 cosech

Math.cosech() -> I<Obj>

Return the

=cut

=head2 cosh

Math.cosh() -> I<Obj>

Return the

=cut

=head2 cot

Math.cot() -> I<Obj>

Return the

=cut

=head2 cotan

Math.cotan() -> I<Obj>

Return the

=cut

=head2 cotanh

Math.cotanh() -> I<Obj>

Return the

=cut

=head2 coth

Math.coth() -> I<Obj>

Return the

=cut

=head2 csc

Math.csc() -> I<Obj>

Return the

=cut

=head2 csch

Math.csch() -> I<Obj>

Return the

=cut

=head2 deg2deg

Math.deg2deg() -> I<Obj>

Return the

=cut

=head2 deg2grad

Math.deg2grad() -> I<Obj>

Return the

=cut

=head2 deg2rad

Math.deg2rad() -> I<Obj>

Return the

=cut

=head2 gcd

Math.gcd() -> I<Obj>

Return the

=cut

=head2 get_constant

Math.get_constant() -> I<Obj>

Return the

=cut

=head2 grad2deg

Math.grad2deg() -> I<Obj>

Return the

=cut

=head2 grad2grad

Math.grad2grad() -> I<Obj>

Return the

=cut

=head2 grad2rad

Math.grad2rad() -> I<Obj>

Return the

=cut

=head2 lcm

Math.lcm() -> I<Obj>

Return the

=cut

=head2 map

Math.map() -> I<Obj>

Return the

=cut

=head2 map_range

Math.map_range() -> I<Obj>

Return the

=cut

=head2 max

Math.max() -> I<Obj>

Return the

=cut

=head2 min

Math.min() -> I<Obj>

Return the

=cut

=head2 num2percent

Math.num2percent() -> I<Obj>

Return the

Aliases: I<number_to_percentage>

=cut

=head2 rad2deg

Math.rad2deg() -> I<Obj>

Return the

=cut

=head2 rad2grad

Math.rad2grad() -> I<Obj>

Return the

=cut

=head2 rad2rad

Math.rad2rad() -> I<Obj>

Return the

=cut

=head2 rand

Math.rand() -> I<Obj>

Return the

=cut

=head2 range_sum

Math.range_sum() -> I<Obj>

Return the

=cut

=head2 sec

Math.sec() -> I<Obj>

Return the

=cut

=head2 sech

Math.sech() -> I<Obj>

Return the

=cut

=head2 sinh

Math.sinh() -> I<Obj>

Return the

=cut

=head2 sum

Math.sum() -> I<Obj>

Return the

=cut

=head2 tan

Math.tan() -> I<Obj>

Return the

=cut

=head2 tanh

Math.tanh() -> I<Obj>

Return the

=cut
