
=encoding utf8

=head1 NAME

Sidef::Sys::Sig

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Sig.new(...);

=head1 METHODS


=head2 ABRT

Sig.ABRT() -> I<Obj>

Return the

=cut

=head2 ALRM

Sig.ALRM() -> I<Obj>

Return the

=cut

=head2 BUS

Sig.BUS() -> I<Obj>

Return the

=cut

=head2 CHLD

Sig.CHLD() -> I<Obj>

Return the

=cut

=head2 CLD

Sig.CLD() -> I<Obj>

Return the

=cut

=head2 CONT

Sig.CONT() -> I<Obj>

Return the

=cut

=head2 FPE

Sig.FPE() -> I<Obj>

Return the

=cut

=head2 HUP

Sig.HUP() -> I<Obj>

Return the

=cut

=head2 ILL

Sig.ILL() -> I<Obj>

Return the

=cut

=head2 INT

Sig.INT() -> I<Obj>

Return the

=cut

=head2 IO

Sig.IO() -> I<Obj>

Return the

=cut

=head2 IOT

Sig.IOT() -> I<Obj>

Return the

=cut

=head2 KILL

Sig.KILL() -> I<Obj>

Return the

=cut

=head2 new

Sig.new() -> I<Obj>

Return the

=cut

=head2 NUM32

Sig.NUM32() -> I<Obj>

Return the

=cut

=head2 NUM33

Sig.NUM33() -> I<Obj>

Return the

=cut

=head2 NUM35

Sig.NUM35() -> I<Obj>

Return the

=cut

=head2 NUM36

Sig.NUM36() -> I<Obj>

Return the

=cut

=head2 NUM37

Sig.NUM37() -> I<Obj>

Return the

=cut

=head2 NUM38

Sig.NUM38() -> I<Obj>

Return the

=cut

=head2 NUM39

Sig.NUM39() -> I<Obj>

Return the

=cut

=head2 NUM40

Sig.NUM40() -> I<Obj>

Return the

=cut

=head2 NUM41

Sig.NUM41() -> I<Obj>

Return the

=cut

=head2 NUM42

Sig.NUM42() -> I<Obj>

Return the

=cut

=head2 NUM43

Sig.NUM43() -> I<Obj>

Return the

=cut

=head2 NUM44

Sig.NUM44() -> I<Obj>

Return the

=cut

=head2 NUM45

Sig.NUM45() -> I<Obj>

Return the

=cut

=head2 NUM46

Sig.NUM46() -> I<Obj>

Return the

=cut

=head2 NUM47

Sig.NUM47() -> I<Obj>

Return the

=cut

=head2 NUM48

Sig.NUM48() -> I<Obj>

Return the

=cut

=head2 NUM49

Sig.NUM49() -> I<Obj>

Return the

=cut

=head2 NUM50

Sig.NUM50() -> I<Obj>

Return the

=cut

=head2 NUM51

Sig.NUM51() -> I<Obj>

Return the

=cut

=head2 NUM52

Sig.NUM52() -> I<Obj>

Return the

=cut

=head2 NUM53

Sig.NUM53() -> I<Obj>

Return the

=cut

=head2 NUM54

Sig.NUM54() -> I<Obj>

Return the

=cut

=head2 NUM55

Sig.NUM55() -> I<Obj>

Return the

=cut

=head2 NUM56

Sig.NUM56() -> I<Obj>

Return the

=cut

=head2 NUM57

Sig.NUM57() -> I<Obj>

Return the

=cut

=head2 NUM58

Sig.NUM58() -> I<Obj>

Return the

=cut

=head2 NUM59

Sig.NUM59() -> I<Obj>

Return the

=cut

=head2 NUM60

Sig.NUM60() -> I<Obj>

Return the

=cut

=head2 NUM61

Sig.NUM61() -> I<Obj>

Return the

=cut

=head2 NUM62

Sig.NUM62() -> I<Obj>

Return the

=cut

=head2 NUM63

Sig.NUM63() -> I<Obj>

Return the

=cut

=head2 PIPE

Sig.PIPE() -> I<Obj>

Return the

=cut

=head2 POLL

Sig.POLL() -> I<Obj>

Return the

=cut

=head2 PROF

Sig.PROF() -> I<Obj>

Return the

=cut

=head2 PWR

Sig.PWR() -> I<Obj>

Return the

=cut

=head2 QUIT

Sig.QUIT() -> I<Obj>

Return the

=cut

=head2 RTMAX

Sig.RTMAX() -> I<Obj>

Return the

=cut

=head2 RTMIN

Sig.RTMIN() -> I<Obj>

Return the

=cut

=head2 SEGV

Sig.SEGV() -> I<Obj>

Return the

=cut

=head2 STKFLT

Sig.STKFLT() -> I<Obj>

Return the

=cut

=head2 STOP

Sig.STOP() -> I<Obj>

Return the

=cut

=head2 SYS

Sig.SYS() -> I<Obj>

Return the

=cut

=head2 TERM

Sig.TERM() -> I<Obj>

Return the

=cut

=head2 TRAP

Sig.TRAP() -> I<Obj>

Return the

=cut

=head2 TSTP

Sig.TSTP() -> I<Obj>

Return the

=cut

=head2 TTIN

Sig.TTIN() -> I<Obj>

Return the

=cut

=head2 TTOU

Sig.TTOU() -> I<Obj>

Return the

=cut

=head2 UNUSED

Sig.UNUSED() -> I<Obj>

Return the

=cut

=head2 URG

Sig.URG() -> I<Obj>

Return the

=cut

=head2 USR1

Sig.USR1() -> I<Obj>

Return the

=cut

=head2 USR2

Sig.USR2() -> I<Obj>

Return the

=cut

=head2 VTALRM

Sig.VTALRM() -> I<Obj>

Return the

=cut

=head2 WINCH

Sig.WINCH() -> I<Obj>

Return the

=cut

=head2 XCPU

Sig.XCPU() -> I<Obj>

Return the

=cut

=head2 XFSZ

Sig.XFSZ() -> I<Obj>

Return the

=cut
