
=encoding utf8

=head1 NAME

Sidef::Types::Regex::Match

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Match(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 ...

    a ... b

Returns the

=cut

=head2 cap

    Match.cap()

Returns the

Aliases: I<to_a>, I<caps>, I<to_array>, I<captures>

=cut

=head2 dump

    Match.dump()

Returns the

=cut

=head2 join

    Match.join()

Returns the

=cut

=head2 ncap

    Match.ncap()

Returns the

Aliases: I<ncaps>, I<named_captures>

=cut

=head2 pos

    Match.pos()

Returns the

Aliases: I<match_pos>

=cut

=head2 regex

    Match.regex()

Returns the

=cut

=head2 string

    Match.string()

Returns the

=cut

=head2 to_bool

    Match.to_bool()

Returns the

Aliases: I<matched>, I<is_successful>

=cut

=head2 to_s

    Match.to_s()

Returns the

Aliases: I<to_str>

=cut
