
=encoding utf8

=head1 NAME

Sidef::Types::Regex::Match

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Match(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 ...

    a ... b

Returns the

=cut

=head2 cap

    self.cap

Returns the

Aliases: I<to_a>, I<caps>, I<groups>, I<to_array>, I<captures>

=cut

=head2 dump

    self.dump

Returns the

=cut

=head2 join

    self.join(sep)

Returns the

=cut

=head2 ncap

    self.ncap

Returns the

Aliases: I<ncaps>, I<named_groups>, I<named_captures>

=cut

=head2 pos

    self.pos

Returns the

Aliases: I<match_pos>

=cut

=head2 regex

    self.regex

Returns the

=cut

=head2 string

    self.string

Returns the

=cut

=head2 to_bool

    self.to_bool

Returns the

Aliases: I<matched>, I<is_successful>

=cut

=head2 to_s

    self.to_s

Returns the

Aliases: I<to_str>

=cut
