
=encoding utf8

=head1 NAME

Sidef::Types::Regex::Matches

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Matches.new(...));

=head1 METHODS


=head2 ??

I<Num> B<??> I<Num> -> I<Num>

Return the

=cut

=head2 captures

Matches.captures() -> I<Bool>

Return the

=cut

=head2 isSuccessful

Matches.isSuccessful() -> I<Bool>

Return the

=cut

=head2 is_successful

Matches.is_successful() -> I<Bool>

Return the

=cut

=head2 matched

Matches.matched() -> I<Bool>

Return the

=cut

=head2 matches

Matches.matches() -> I<Bool>

Return the

=cut

=head2 namedCaptures

Matches.namedCaptures() -> I<Bool>

Return the

=cut

=head2 named_captures

Matches.named_captures() -> I<Bool>

Return the

=cut

=head2 namedMatches

Matches.namedMatches() -> I<Bool>

Return the

=cut

=head2 named_matches

Matches.named_matches() -> I<Bool>

Return the

=cut

=head2 pos

Matches.pos() -> I<Bool>

Return the

=cut

=head2 toBool

Matches.toBool() -> I<Bool>

Return the

=cut

=head2 to_bool

Matches.to_bool() -> I<Bool>

Return the

=cut
