
=encoding utf8

=head1 NAME

Sidef::Types::Regex::Regex

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Regex.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef::Convert::Convert

=head1 METHODS


=head2 =~

I<Num> B<=~> I<Num> -> I<Num>

Return the

=cut

=head2 dump

Regex.dump() -> I<Bool>

Return the

=cut

=head2 get_value

Regex.get_value() -> I<Bool>

Return the

=cut

=head2 gmatch

Regex.gmatch() -> I<Bool>

Return the

=cut

=head2 gmatches

Regex.gmatches() -> I<Bool>

Return the

=cut

=head2 match

Regex.match() -> I<Bool>

Return the

=cut

=head2 matches

Regex.matches() -> I<Bool>

Return the

=cut
