{
  Array   => {
               Array => {
                 inherits => ["Convert::Convert", "Sidef"],
                 methods  => [
                               { args => ["array"], name => "&" },
                               { args => ["array"], name => "&&" },
                               { args => ["array"], name => "+", returns => "Array::Array" },
                               { args => ["obj"], name => "++", returns => "Array::Array" },
                               {
                                 args    => ["array"],
                                 doc     => "Substract the I<array> from the self array.",
                                 name    => "-",
                                 returns => "Array::Array",
                               },
                               { args => [], name => "--", returns => "Array::Array" },
                               { args => ["number"], name => "<<", returns => "Array::Array" },
                               { args => ["arg"], name => "=", returns => "Array::Array" },
                               { args => ["array"], name => "==", returns => "Bool::Bool" },
                               { args => ["number"], name => ">>", returns => "Array::Array" },
                               { args => ["array"], name => "^" },
                               { args => ["array", "bool"], name => "_grep" },
                               { args => ["method"], name => "_min_max" },
                               { args => ["obj"], name => "contains", returns => "Bool::Bool" },
                               { args => [], name => "dump" },
                               { args => ["index", "..."], name => "insert", returns => "Array::Array" },
                               { args => ["separator"], name => "join", returns => "String::String" },
                               { args => [], name => "len", returns => "Number::Integer" },
                               { args => [], name => "length", returns => "Number::Number" },
                               { args => ["size", "type"], name => "make", returns => "Array::Array" },
                               { args => ["code"], name => "map" },
                               { name => "max" },
                               { name => "min" },
                               { args => [], name => "offset", returns => "Number::Number" },
                               {
                                 args => ["index"],
                                 doc  => "Remove and return the last element from the self array.",
                                 name => "pop",
                               },
                               { args => ["..."], name => "push", returns => "Array::Array" },
                               { args => [], name => "range", returns => "Array::Array" },
                               { args => [], name => "reverse", returns => "Array::Array" },
                               { args => [], name => "shift" },
                               { args => [], name => "to_hash", returns => "Hash::Hash" },
                               { args => ["..."], name => "unshift", returns => "Array::Array" },
                               { args => ["array"], name => "|" },
                             ],
               },
             },
  Black   => {
               Hole => { methods => [{ name => "AUTOLOAD", returns => "Black::Hole" }] },
             },
  Block   => {
               Code => {
                 inherits => ["Sidef"],
                 methods  => [
                               { args => ["code"], name => "&&" },
                               { args => ["num"], name => "*", returns => "Block::Code" },
                               { args => ["code"], name => ":", returns => "Block::Code" },
                               { args => ["code"], name => "?" },
                               { args => ["..."], name => "call" },
                               { args => [], name => "exec", returns => "Block::Code" },
                               { args => ["arg"], name => "for", returns => "Block::Code" },
                               { args => [], name => "given", returns => "Block::Switch" },
                               { args => ["bool"], name => "if", returns => "Block::Code" },
                               { args => [], name => "run" },
                               { args => [], name => "to_hash", returns => "Hash::Hash" },
                               { args => ["condition"], name => "while", returns => "Block::Code" },
                               { args => ["code"], name => "||" },
                             ],
               },
               Continue => { methods => [{ name => "continue" }] },
               Do => {
                 inherits => ["Sidef"],
                 methods  => [{ args => ["code"], name => "do", returns => "Block::Do" }],
               },
               Switch => {
                 inherits => ["Block::Do", "Sidef"],
                 methods  => [
                               { args => ["code"], name => "default" },
                               { args => [], name => "end", returns => "Black::Hole" },
                               { args => [], name => "value" },
                               { args => ["arg"], name => "when", returns => "Block::Switch" },
                             ],
               },
             },
  Bool    => {
               Bool => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => ["bool"], name => "!", returns => "Bool::Bool" },
                               { args => ["code"], name => "&&" },
                               { args => ["code"], name => "?", returns => "Bool::Ternary" },
                               { args => [], name => "dump", returns => "String::String" },
                               {
                                 args    => [],
                                 doc     => "Returns a false value.",
                                 name    => "false",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Returns true if the value is false.",
                                 name    => "is_false",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Returns true if the value is true.",
                                 name    => "is_true",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "not" },
                               {
                                 args    => [],
                                 doc     => "Returns a true value.",
                                 name    => "true",
                                 returns => "Bool::Bool",
                               },
                               { args => ["code"], name => "||" },
                             ],
               },
               If => {
                 inherits => ["Block::Do", "Sidef"],
                 methods  => [
                               { args => ["code"], name => "else" },
                               { args => ["code"], name => "elsif" },
                               { args => ["arg"], name => "if", returns => "Bool::If" },
                             ],
               },
               Ternary => {
                 inherits => ["Sidef"],
                 methods  => [{ args => ["code"], name => ":" }],
               },
               While => {
                 inherits => ["Sidef"],
                 methods  => [
                               { args => ["code"], name => "do", returns => "Bool::While" },
                               { args => ["code"], name => "while" },
                             ],
               },
             },
  Byte    => {
               Byte  => { inherits => ["Convert::Convert", "Number::Number"] },
               Bytes => {
                          inherits => ["Convert::Convert", "Array::Array"],
                          methods  => [{ args => [], name => "join", returns => "String::String" }],
                        },
             },
  Char    => {
               Char  => { inherits => ["Convert::Convert", "String::String"] },
               Chars => { inherits => ["Convert::Convert", "Array::Array"] },
             },
  Convert => {
               Convert => {
                 methods => [
                   { args => [], name => "to_a" },
                   { args => [], name => "to_b" },
                   { args => [], name => "to_dir" },
                   { args => [], name => "to_f" },
                   { args => [], name => "to_file" },
                   {
                     args    => [],
                     doc     => "Converts the object into an integer.",
                     name    => "to_i",
                     returns => "Number::Integer",
                   },
                   {
                     args    => [],
                     doc     => "Converts the object into a string.",
                     name    => "to_s",
                     returns => "String::String",
                   },
                   {
                     args    => [],
                     doc     => "Converts the object into a double quoted string.",
                     name    => "to_sd",
                     returns => "String::Double",
                   },
                 ],
               },
             },
  Glob    => {
               Dir => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => [], name => "abs_name", returns => "Glob::Dir" },
                               {
                                 args    => [],
                                 doc     => "Creates the self directory.",
                                 name    => "create",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Creates the self directory with needed parents.",
                                 name    => "create_tree",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Returns the parent of the self directory.",
                                 name    => "parent",
                                 returns => "Glob::Dir",
                               },
                               {
                                 args    => [],
                                 doc     => "Removes the self directory, only if the directory is empty.",
                                 name    => "remove",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Removes the self directory tree, with all its content.",
                                 name    => "remove_tree",
                                 returns => "Bool::Bool",
                               },
                             ],
               },
               File => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => [], name => "abs_name", returns => "Glob::File" },
                               { args => [], name => "basename", returns => "String::String" },
                               { args => [], name => "dirname", returns => "Glob::Dir" },
                               { args => [], name => "dump", returns => "String::String" },
                               {
                                 args    => [],
                                 doc     => "Returns true if the self file exists.",
                                 name    => "exists",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "is_binary", returns => "Bool::Bool" },
                               { args => [], name => "is_file", returns => "Bool::Bool" },
                               { args => [], name => "is_text", returns => "Bool::Bool" },
                               { args => [], name => "name", returns => "String::String" },
                               { args => ["mode"], name => "open", returns => "Glob::FileHandle" },
                               { args => [], name => "open_a", returns => "Glob::FileHandle" },
                               { args => [], name => "open_r", returns => "Glob::FileHandle" },
                               { args => [], name => "open_w", returns => "Glob::FileHandle" },
                               { args => [], name => "size", returns => "Number::Number" },
                             ],
               },
               FileHandle => {
                 methods => [
                   { args => [], name => "close", returns => "Bool::Bool" },
                   { args => [], name => "file", returns => "Glob::File" },
                   { args => [], name => "readline", returns => "String::String" },
                   { args => ["string"], name => "write", returns => "Bool::Bool" },
                 ],
               },
               Pipe => {
                 methods => [
                   { args => [], name => "command", returns => "String::String" },
                   { args => [], name => "dump", returns => "String::String" },
                   { args => ["mode"], name => "open", returns => "Glob::PipeHandle" },
                   { args => [], name => "open_r", returns => "Glob::Pipe" },
                   { args => [], name => "open_w", returns => "Glob::Pipe" },
                 ],
               },
               PipeHandle => {
                 methods => [
                   { args => [], name => "close", returns => "Bool::Bool" },
                   { args => [], name => "command", returns => "String::String" },
                   { args => [], name => "pipe" },
                   { args => [], name => "readline" },
                 ],
               },
             },
  Hash    => {
               Hash => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => ["hash"], name => "+", returns => "Hash::Hash" },
                               { args => [], name => "flip" },
                               { name => "keys", returns => "Array::Array" },
                               { args => ["keys", "struct"], name => "map", returns => "Hash::Hash" },
                               { name => "values", returns => "Array::Array" },
                             ],
               },
             },
  Nil     => {
               Nil => {
                        inherits => ["Convert::Convert", "Sidef"],
                        methods  => [{ name => "dump", returns => "String::String" }],
                      },
             },
  Number  => {
               Float   => { inherits => ["Number", "Number::Number"] },
               Integer => { inherits => ["Number", "Number::Number"] },
               Number  => {
                            inherits => ["Convert::Convert", "Sidef"],
                            methods  => [
                                          { args => ["num"], name => "!=", returns => "Bool::Bool" },
                                          { args => ["num"], name => "%", returns => "Number::Number" },
                                          { args => ["num"], name => "*", returns => "Number::Number" },
                                          { args => ["num"], name => "**", returns => "Number::Number" },
                                          { args => ["num"], name => "+", returns => "Number::Number" },
                                          { args => [], name => "++", returns => "Number::Number" },
                                          { args => ["num"], name => "-", returns => "Number::Number" },
                                          { args => [], name => "--", returns => "Number::Number" },
                                          { args => ["num"], name => "..", returns => "Array::Array" },
                                          {
                                            args    => ["num"],
                                            doc     => "Divides the self number to I<num> and returns the result.",
                                            name    => "/",
                                            returns => "Number::Number",
                                          },
                                          { args => ["num"], name => "<", returns => "Bool::Bool" },
                                          { args => ["num"], name => "<=", returns => "Bool::Bool" },
                                          { args => ["num"], name => "==", returns => "Bool::Bool" },
                                          { args => ["num"], name => ">", returns => "Bool::Bool" },
                                          { args => ["num"], name => ">=", returns => "Bool::Bool" },
                                          { args => [], name => "abs", returns => "Number::Number" },
                                          { args => [], name => "chr", returns => "Char::Char" },
                                          { args => [], name => "commify", returns => "String::String" },
                                          { args => [], name => "dump", returns => "String::String" },
                                          { args => [], name => "int", returns => "Number::Number" },
                                          { args => [], name => "is_even", returns => "Bool::Bool" },
                                          { args => [], name => "is_integer", returns => "Bool::Bool" },
                                          { args => [], name => "is_negative", returns => "Bool::Bool" },
                                          { args => [], name => "is_odd", returns => "Bool::Bool" },
                                          { args => [], name => "is_positive", returns => "Bool::Bool" },
                                          { args => [], name => "log", returns => "Number::Number" },
                                          { args => [], name => "log10", returns => "Number::Number" },
                                          { args => [], name => "log2", returns => "Number::Number" },
                                          {
                                            args    => [],
                                            doc     => "Returns the next power of two for the self number.",
                                            name    => "next_power_of_two",
                                            returns => "Number::Number",
                                          },
                                          {
                                            args    => [],
                                            doc     => "Returns the positive square root of the self number.",
                                            name    => "sqrt",
                                            returns => "Number::Number",
                                          },
                                        ],
                          },
             },
  Regex   => {
               Regex => {
                 inherits => ["Convert", "String::Double", "Double", "Convert::Convert"],
                 methods  => [
                               { args => [], name => "dump", returns => "String::String" },
                               { args => ["object"], name => "matches", returns => "Bool::Bool" },
                             ],
               },
             },
  String  => {
               Double => {
                           inherits => ["String", "String::String"],
                           methods  => [
                                         { args => [], name => "apply_escapes", returns => "String::Double" },
                                       ],
                         },
               String => {
                           inherits => ["Convert::Convert", "Sidef"],
                           methods  => [
                                         { args => ["string"], name => "!=", returns => "Bool::Bool" },
                                         { args => ["num"], name => "*", returns => "String::String" },
                                         { args => ["string"], name => "+", returns => "String::String" },
                                         { args => [], name => "--", returns => "String::String" },
                                         { args => ["string"], name => "..", returns => "Array::Array" },
                                         { args => ["string"], name => "<", returns => "Bool::Bool" },
                                         { args => ["string"], name => "<=", returns => "Bool::Bool" },
                                         { args => ["string"], name => "==", returns => "Bool::Bool" },
                                         { name => "=~" },
                                         { args => ["string"], name => ">", returns => "Bool::Bool" },
                                         { args => ["string"], name => ">=", returns => "Bool::Bool" },
                                         { args => [], name => "apply_escapes", returns => "String::String" },
                                         {
                                           args    => [],
                                           doc     => "Chops off the last character from the self string only if it is a newline character.",
                                           name    => "chomp",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => [],
                                           doc     => "Chops off the last character from the self string and returns it.",
                                           name    => "chop",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => ["string", "start_pos"],
                                           name    => "contains",
                                           returns => "Bool::Bool",
                                         },
                                         { args => [], name => "dump", returns => "String::String" },
                                         { args => [], name => "eval" },
                                         {
                                           args    => ["string", "pos", "len"],
                                           name    => "insert",
                                           returns => "String::String",
                                         },
                                         { args => ["delim", "..."], name => "join", returns => "String::String" },
                                         {
                                           args    => [],
                                           doc     => "Lowercases the self string and returns it.",
                                           name    => "lc",
                                           returns => "String::String",
                                         },
                                         { args => [], name => "lcfirst", returns => "String::String" },
                                         { args => [], name => "length", returns => "Number::Number" },
                                         { args => [], name => "ord", returns => "Byte::Byte" },
                                         { args => [], name => "print", returns => "Bool::Bool" },
                                         { args => ["..."], name => "printf", returns => "Bool::Bool" },
                                         { args => [], name => "reverse", returns => "String::String" },
                                         { args => [], name => "say", returns => "Bool::Bool" },
                                         { args => ["..."], name => "sprintf", returns => "String::String" },
                                         { args => [], name => "stat_dir", returns => "Glob::Dir" },
                                         {
                                           args    => [],
                                           doc     => "Returns a file object for the self string.",
                                           name    => "stat_file",
                                           returns => "Glob::File",
                                         },
                                         {
                                           args    => ["offs", "len"],
                                           doc     => "Extracts a substring out of the self string and returns it. First character is at offset zero. If I<offs> is negative, starts that far back from the end of the string. If I<len> is omitted, returns everything through the end of the string. If I<len> is negative, leaves that many characters off the end of the string.",
                                           name    => "substr",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => [],
                                           doc     => "Uppercases the self string and returns it.",
                                           name    => "uc",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => [],
                                           doc     => "Uppercases the first letter of the self string and returns the string.",
                                           name    => "ucfirst",
                                           returns => "String::String",
                                         },
                                       ],
                         },
             },
}