{
  Array   => {
               Array => {
                 inherits => ["Convert::Convert", "Sidef"],
                 methods  => [
                               { args => ["array"], name => "&" },
                               { args => ["array"], name => "&&" },
                               { args => ["array"], name => "+", returns => "Array::Array" },
                               { args => ["obj"], name => "++", returns => "Array::Array" },
                               {
                                 args    => ["array"],
                                 doc     => "Substract the I<array> from the self array.",
                                 name    => "-",
                                 returns => "Array::Array",
                               },
                               { args => [], name => "--", returns => "Array::Array" },
                               { args => ["number"], name => "<<", returns => "Array::Array" },
                               { args => ["arg"], name => "=", returns => "Array::Array" },
                               { args => ["array"], name => "==", returns => "Bool::Bool" },
                               { args => ["number"], name => ">>", returns => "Array::Array" },
                               { args => ["array"], name => "^" },
                               { args => ["array", "bool"], name => "_grep" },
                               { args => ["method"], name => "_min_max" },
                               { args => ["method"], name => "_op_equal" },
                               { args => ["code"], name => "all", returns => "Bool::Bool" },
                               { args => ["obj"], name => "contains", returns => "Bool::Bool" },
                               { args => ["index"], name => "defined", returns => "Bool::Bool" },
                               { name => "divide" },
                               { args => ["amount"], name => "dropLeft", returns => "Array::Array" },
                               { args => ["amount"], name => "dropRight", returns => "Array::Array" },
                               { args => [], name => "dump" },
                               { args => ["index"], name => "exists", returns => "Bool::Bool" },
                               { args => ["code"], name => "find" },
                               { args => [], name => "first" },
                               { args => ["code"], name => "first_index", returns => "Number::Number" },
                               { args => ["from", "to"], name => "ft", returns => "Array::Array" },
                               { args => [], name => "get_value" },
                               { args => ["code"], name => "grep" },
                               { args => ["index", "..."], name => "insert", returns => "Array::Array" },
                               { args => ["delim"], name => "join", returns => "String::String" },
                               { args => ["delim_obj"], name => "join_insert" },
                               { args => [], name => "last" },
                               { args => ["code"], name => "last_index", returns => "Number::Number" },
                               { args => [], name => "len", returns => "Number::Integer" },
                               { args => [], name => "length", returns => "Number::Number" },
                               { args => ["size", "type"], name => "make", returns => "Array::Array" },
                               { args => ["code"], name => "map" },
                               { name => "max" },
                               { args => ["array"], name => "mesh" },
                               { name => "min" },
                               { name => "multiply" },
                               { args => [], name => "offset", returns => "Number::Number" },
                               {
                                 args => ["index"],
                                 doc  => "Remove and return the last element from the self array.",
                                 name => "pop",
                               },
                               { args => ["..."], name => "push", returns => "Array::Array" },
                               { args => [], name => "range", returns => "Array::Array" },
                               { args => ["method"], name => "reduce" },
                               { args => ["method"], name => "reducePairs" },
                               { args => [], name => "reverse", returns => "Array::Array" },
                               { args => [], name => "shift" },
                               { args => [], name => "shuffle", returns => "Array::Array" },
                               { args => [], name => "sliceReverse" },
                               { args => ["offset", "length", "array"], name => "splice" },
                               { name => "sum" },
                               { args => ["amount"], name => "takeLeft", returns => "Array::Array" },
                               { args => ["amount"], name => "takeRight", returns => "Array::Array" },
                               { args => [], name => "to_hash", returns => "Hash::Hash" },
                               { args => [], name => "unique", returns => "Array::Array" },
                               { args => ["..."], name => "unshift", returns => "Array::Array" },
                               { args => ["array"], name => "|" },
                             ],
               },
             },
  Black   => {
               Hole => {
                 methods => [
                   { name => "AUTOLOAD", returns => "Black::Hole" },
                   { name => "DESTROY" },
                 ],
               },
             },
  Block   => {
               Break    => { methods => [{ name => "break" }] },
               Code     => {
                             inherits => ["Sidef"],
                             methods  => [
                                           { args => ["code"], name => "&&" },
                                           { args => ["num"], name => "*", returns => "Block::Code" },
                                           { args => ["code"], name => ":", returns => "Block::Code" },
                                           { args => ["code"], name => "?" },
                                           { args => [], name => "_run_code" },
                                           { args => ["..."], name => "call" },
                                           { args => [], name => "exec", returns => "Block::Code" },
                                           { args => ["arg"], name => "for", returns => "Block::Code" },
                                           { args => [], name => "given", returns => "Block::Switch" },
                                           { args => ["bool"], name => "if", returns => "Block::Code" },
                                           { args => [], name => "run" },
                                           { args => [], name => "to_hash", returns => "Hash::Hash" },
                                           { args => ["condition"], name => "while", returns => "Block::Code" },
                                           { args => ["code"], name => "||" },
                                         ],
                           },
               Continue => { methods => [{ name => "continue" }] },
               Do       => {
                             inherits => ["Sidef"],
                             methods  => [{ args => ["code"], name => "do", returns => "Block::Do" }],
                           },
               For      => {
                             methods => [
                               { args => ["code"], name => "do" },
                               { args => ["code"], name => "for", returns => "Block::For" },
                             ],
                           },
               Given    => {
                             methods => [
                               { args => ["expr"], name => "given", returns => "Block::Switch" },
                             ],
                           },
               Return   => {
                             methods => [
                               { name => "get_obj" },
                               { args => ["obj"], name => "return", returns => "Block::Return" },
                             ],
                           },
               Switch   => {
                             inherits => ["Block::Do", "Sidef"],
                             methods  => [
                                           { args => ["code"], name => "default" },
                                           { args => [], name => "end", returns => "Black::Hole" },
                                           { args => [], name => "value" },
                                           { args => ["arg"], name => "when", returns => "Block::Switch" },
                                         ],
                           },
             },
  Bool    => {
               Bool => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => ["bool"], name => "!", returns => "Bool::Bool" },
                               { args => ["code"], name => "&&" },
                               { args => ["code"], name => "?", returns => "Bool::Ternary" },
                               { args => ["code"], name => "and" },
                               { args => [], name => "dump", returns => "String::String" },
                               {
                                 args    => [],
                                 doc     => "Returns a false value.",
                                 name    => "false",
                                 returns => "Bool::Bool",
                               },
                               { name => "get_value" },
                               {
                                 args    => [],
                                 doc     => "Returns true if the value is false.",
                                 name    => "is_false",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Returns true if the value is true.",
                                 name    => "is_true",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "not" },
                               { args => ["code"], name => "or" },
                               {
                                 args    => [],
                                 doc     => "Returns a true value.",
                                 name    => "true",
                                 returns => "Bool::Bool",
                               },
                               { args => ["code"], name => "||" },
                             ],
               },
               If => {
                 inherits => ["Block::Do", "Sidef"],
                 methods  => [
                               { args => ["code"], name => "else" },
                               { args => ["code"], name => "elsif" },
                               { args => ["arg"], name => "if", returns => "Bool::If" },
                             ],
               },
               Ternary => {
                 inherits => ["Sidef"],
                 methods  => [{ args => ["code"], name => ":", returns => "Block::Code" }],
               },
               While => {
                 inherits => ["Sidef"],
                 methods  => [
                               { args => ["code"], name => "do", returns => "Bool::While" },
                               { args => ["code"], name => "while", returns => "Bool::While" },
                             ],
               },
             },
  Byte    => {
               Byte  => { inherits => ["Convert::Convert", "Number::Number"] },
               Bytes => {
                          inherits => ["Convert::Convert", "Array::Array"],
                          methods  => [{ args => [], name => "join", returns => "String::String" }],
                        },
             },
  Char    => {
               Char  => { inherits => ["Convert::Convert", "String::String"] },
               Chars => { inherits => ["Convert::Convert", "Array::Array"] },
             },
  Convert => {
               Convert => {
                 methods => [
                   { args => [], name => "to_a" },
                   { args => [], name => "to_b" },
                   { args => [], name => "to_dir" },
                   { args => [], name => "to_f" },
                   { args => [], name => "to_file" },
                   {
                     args    => [],
                     doc     => "Converts the object into an integer.",
                     name    => "to_i",
                     returns => "Number::Integer",
                   },
                   {
                     args    => [],
                     doc     => "Converts the object into a string.",
                     name    => "to_s",
                     returns => "String::String",
                   },
                   {
                     args    => [],
                     doc     => "Converts the object into a double quoted string.",
                     name    => "to_sd",
                     returns => "String::Double",
                   },
                 ],
               },
             },
  Glob    => {
               Backtick => {
                 methods => [
                   { args => [], name => "_run" },
                   { args => [], name => "getLines", returns => "Array::Array" },
                   { args => [], name => "getString", returns => "String::String" },
                 ],
               },
               Dir => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => [], name => "abs_name", returns => "Glob::Dir" },
                               { args => [], name => "chdir", returns => "Bool::Bool" },
                               {
                                 args    => [],
                                 doc     => "Creates the self directory.",
                                 name    => "create",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Creates the self directory with needed parents.",
                                 name    => "create_tree",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "exists", returns => "Bool::Bool" },
                               { name => "get_value" },
                               { args => [], name => "open", returns => "Glob::DirHandle" },
                               {
                                 args    => [],
                                 doc     => "Returns the parent of the self directory.",
                                 name    => "parent",
                                 returns => "Glob::Dir",
                               },
                               {
                                 args    => [],
                                 doc     => "Removes the self directory, only if the directory is empty.",
                                 name    => "remove",
                                 returns => "Bool::Bool",
                               },
                               {
                                 args    => [],
                                 doc     => "Removes the self directory tree, with all its content.",
                                 name    => "remove_tree",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "split" },
                             ],
               },
               DirHandle => {
                 methods => [
                   { args => [], name => "close", returns => "Bool::Bool" },
                   { name => "dir" },
                   { args => [], name => "get_file", returns => "Glob::File" },
                   { args => [], name => "get_files", returns => "Array::Array" },
                   { args => [], name => "lstat", returns => "Glob::Stat" },
                   { args => ["pos"], name => "seek", returns => "Bool::Bool" },
                   { args => [], name => "stat", returns => "Glob::Stat" },
                   { args => [], name => "tell", returns => "Number::Number" },
                 ],
               },
               File => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => [], name => "abs_name", returns => "Glob::File" },
                               { args => [], name => "access_time_days_diff", returns => "Bool::Bool" },
                               { args => [], name => "basename", returns => "String::String" },
                               { args => [], name => "change_time_days_diff" },
                               { args => [], name => "dirname", returns => "Glob::Dir" },
                               { args => [], name => "dump", returns => "String::String" },
                               {
                                 args    => [],
                                 doc     => "Returns true if the self file exists.",
                                 name    => "exists",
                                 returns => "Bool::Bool",
                               },
                               { name => "get_value" },
                               { args => [], name => "has_setgid_bit", returns => "Bool::Bool" },
                               { args => [], name => "has_setuid_bit", returns => "Bool::Bool" },
                               { args => [], name => "has_sticky_bit", returns => "Bool::Bool" },
                               { args => [], name => "is_binary", returns => "Bool::Bool" },
                               { args => [], name => "is_block", returns => "Bool::Bool" },
                               { args => [], name => "is_char_device", returns => "Bool::Bool" },
                               { args => [], name => "is_directory", returns => "Bool::Bool" },
                               { args => [], name => "is_empty", returns => "Bool::Bool" },
                               { args => [], name => "is_executable", returns => "Bool::Bool" },
                               { args => [], name => "is_file", returns => "Bool::Bool" },
                               { args => [], name => "is_link", returns => "Bool::Bool" },
                               { args => [], name => "is_owned", returns => "Bool::Bool" },
                               { args => [], name => "is_readable", returns => "Bool::Bool" },
                               { args => [], name => "is_real_executable", returns => "Bool::Bool" },
                               { args => [], name => "is_real_owned", returns => "Bool::Bool" },
                               { args => [], name => "is_real_readable", returns => "Bool::Bool" },
                               { args => [], name => "is_real_writeable", returns => "Bool::Bool" },
                               { args => [], name => "is_socket", returns => "Bool::Bool" },
                               { args => [], name => "is_text", returns => "Bool::Bool" },
                               { args => [], name => "is_writeable", returns => "Bool::Bool" },
                               { args => [], name => "lstat", returns => "Glob::Stat" },
                               {
                                 args    => [],
                                 name    => "modification_time_days_diff",
                                 returns => "Bool::Bool",
                               },
                               { args => [], name => "name", returns => "String::String" },
                               { args => ["mode"], name => "open", returns => "Glob::FileHandle" },
                               { args => [], name => "open_a", returns => "Glob::FileHandle" },
                               { args => [], name => "open_r", returns => "Glob::FileHandle" },
                               { args => [], name => "open_w", returns => "Glob::FileHandle" },
                               { args => [], name => "size", returns => "Number::Number" },
                               { args => [], name => "stat", returns => "Glob::Stat" },
                             ],
               },
               FileHandle => {
                 methods => [
                   { args => [], name => "close", returns => "Bool::Bool" },
                   { args => [], name => "eof", returns => "Bool::Bool" },
                   { args => [], name => "file", returns => "Glob::File" },
                   { name => "get_value" },
                   { name => "is_on_tty", returns => "Bool::Bool" },
                   { args => [], name => "lstat", returns => "Glob::Stat" },
                   { args => [], name => "read_all", returns => "Array::Array" },
                   { args => [], name => "readline", returns => "String::String" },
                   { args => ["pos", "whence"], name => "seek", returns => "Bool::Bool" },
                   { args => [], name => "stat", returns => "Glob::Stat" },
                   { name => "stderr" },
                   { name => "stdin" },
                   { name => "stdout" },
                   { args => [], name => "tell", returns => "Number::Number" },
                   { args => ["string"], name => "write", returns => "Bool::Bool" },
                 ],
               },
               Pipe => {
                 methods => [
                   { args => [], name => "command", returns => "Array::Array" },
                   { args => [], name => "dump", returns => "String::String" },
                   { name => "get_value" },
                   { args => ["mode"], name => "open", returns => "Glob::PipeHandle" },
                   { args => [], name => "open_r", returns => "Glob::Pipe" },
                   { args => [], name => "open_w", returns => "Glob::Pipe" },
                 ],
               },
               PipeHandle => {
                 methods => [
                   { args => [], name => "close", returns => "Bool::Bool" },
                   { args => [], name => "command", returns => "String::String" },
                   { name => "get_value" },
                   { args => [], name => "pipe" },
                   { args => [], name => "read_all", returns => "Array::Array" },
                   { args => [], name => "readline", returns => "String::String" },
                 ],
               },
               Stat => {
                 methods => [
                   { name => "all", returns => "Array::Array" },
                   { args => ["arg", "obj"], name => "lstat", returns => "Glob::Stat" },
                   { name => "parent" },
                   { args => ["arg", "obj"], name => "stat", returns => "Glob::Stat" },
                 ],
               },
             },
  Hash    => {
               Hash => {
                 inherits => ["Convert::Convert"],
                 methods  => [
                               { args => ["obj"], name => "+", returns => "Hash::Hash" },
                               { args => ["key"], name => "exists", returns => "Bool::Bool" },
                               { args => [], name => "flip" },
                               { args => [], name => "get_value" },
                               { args => [], name => "keys", returns => "Array::Array" },
                               { args => ["keys", "struct"], name => "map", returns => "Hash::Hash" },
                               { args => [], name => "values", returns => "Array::Array" },
                             ],
               },
             },
  Nil     => {
               Nil => {
                        inherits => ["Convert::Convert", "Sidef"],
                        methods  => [
                                      { name => "dump", returns => "String::String" },
                                      { name => "get_value" },
                                    ],
                      },
             },
  Number  => {
               Float   => { inherits => ["Number", "Number::Number"] },
               Integer => { inherits => ["Number", "Number::Number"] },
               Number  => {
                            inherits => ["Convert::Convert", "Sidef"],
                            methods  => [
                                          { args => ["num"], name => "!=", returns => "Bool::Bool" },
                                          { args => ["num"], name => "%", returns => "Number::Number" },
                                          { args => ["num"], name => "*", returns => "Number::Number" },
                                          { args => ["num"], name => "**", returns => "Number::Number" },
                                          { args => ["num"], name => "+", returns => "Number::Number" },
                                          { args => [], name => "++", returns => "Number::Number" },
                                          { args => ["num"], name => "-", returns => "Number::Number" },
                                          { args => [], name => "--", returns => "Number::Number" },
                                          { args => ["num"], name => "..", returns => "Array::Array" },
                                          {
                                            args    => ["num"],
                                            doc     => "Divides the self number to I<num> and returns the result.",
                                            name    => "/",
                                            returns => "Number::Number",
                                          },
                                          { args => ["num"], name => "<", returns => "Bool::Bool" },
                                          { args => ["num"], name => "<<", returns => "Number::Number" },
                                          { args => ["num"], name => "<=", returns => "Bool::Bool" },
                                          { args => ["num"], name => "==", returns => "Bool::Bool" },
                                          { args => ["num"], name => ">", returns => "Bool::Bool" },
                                          { args => ["num"], name => ">=", returns => "Bool::Bool" },
                                          { args => ["num"], name => ">>", returns => "Number::Number" },
                                          { args => [], name => "abs", returns => "Number::Number" },
                                          { args => [], name => "chr", returns => "Char::Char" },
                                          { args => [], name => "commify", returns => "String::String" },
                                          { args => [], name => "dump", returns => "String::String" },
                                          { name => "get_value" },
                                          { args => [], name => "hex", returns => "Number::Number" },
                                          { args => [], name => inf, returns => "Number::Number" },
                                          { args => [], name => "int", returns => "Number::Number" },
                                          { args => [], name => "is_even", returns => "Bool::Bool" },
                                          { args => [], name => "is_integer", returns => "Bool::Bool" },
                                          { args => [], name => "is_negative", returns => "Bool::Bool" },
                                          { args => [], name => "is_odd", returns => "Bool::Bool" },
                                          { args => [], name => "is_positive", returns => "Bool::Bool" },
                                          { args => [], name => "log", returns => "Number::Number" },
                                          { args => [], name => "log10", returns => "Number::Number" },
                                          { args => [], name => "log2", returns => "Number::Number" },
                                          {
                                            args    => [],
                                            doc     => "Returns the next power of two for the self number.",
                                            name    => "next_power_of_two",
                                            returns => "Number::Number",
                                          },
                                          { args => [], name => "pi", returns => "Number::Number" },
                                          { args => ["max"], name => "rand", returns => "Number::Number" },
                                          {
                                            args    => [],
                                            doc     => "Returns the positive square root of the self number.",
                                            name    => "sqrt",
                                            returns => "Number::Number",
                                          },
                                          { args => ["n"], name => "sqrt_n", returns => "Number::Number" },
                                          { args => ["num"], name => "to", returns => "Array::Array" },
                                        ],
                          },
             },
  Regex   => {
               Matches => {
                            methods => [
                              { name => "matched", returns => "Bool::Bool" },
                              { args => [], name => "matches", returns => "Array::Array" },
                              { args => [], name => "named_matches" },
                            ],
                          },
               Regex   => {
                            inherits => ["Convert", "String::Double", "Double", "Convert::Convert"],
                            methods  => [
                                          { args => [], name => "dump", returns => "String::String" },
                                          { args => ["object"], name => "matches", returns => "Regex::Matches" },
                                        ],
                          },
             },
  String  => {
               Double => {
                           inherits => ["String", "String::String"],
                           methods  => [
                                         { args => [], name => "apply_escapes", returns => "String::Double" },
                                       ],
                         },
               String => {
                           inherits => ["Convert::Convert", "Sidef"],
                           methods  => [
                                         { args => ["string"], name => "!=", returns => "Bool::Bool" },
                                         { args => ["num"], name => "*", returns => "String::String" },
                                         { args => ["string"], name => "+", returns => "String::String" },
                                         { args => ["string"], name => "-", returns => "String::String" },
                                         { args => [], name => "--", returns => "String::String" },
                                         { args => ["string"], name => "..", returns => "Array::Array" },
                                         { args => ["string"], name => "<", returns => "Bool::Bool" },
                                         { args => ["i"], name => "<<", returns => "String::String" },
                                         { args => ["string"], name => "<=", returns => "Bool::Bool" },
                                         { args => ["string"], name => "==", returns => "Bool::Bool" },
                                         { name => "=~", returns => "Bool::Bool" },
                                         { args => ["string"], name => ">", returns => "Bool::Bool" },
                                         { args => ["string"], name => ">=", returns => "Bool::Bool" },
                                         { args => ["i"], name => ">>", returns => "String::String" },
                                         { args => [], name => "apply_escapes", returns => "String::String" },
                                         { args => ["string"], name => "begins_with", returns => "Bool::Bool" },
                                         { args => ["pos"], name => "charAt", returns => "Char::Char" },
                                         {
                                           args    => [],
                                           doc     => "Chops off the last character from the self string only if it is a newline character.",
                                           name    => "chomp",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => [],
                                           doc     => "Chops off the last character from the self string and returns it.",
                                           name    => "chop",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => ["string", "start_pos"],
                                           name    => "contains",
                                           returns => "Bool::Bool",
                                         },
                                         { args => [], name => "die" },
                                         { args => [], name => "dump", returns => "String::String" },
                                         { args => ["string"], name => "ends_with", returns => "Bool::Bool" },
                                         { args => [], name => "eval" },
                                         { name => "get_value" },
                                         { args => [], name => "glob", returns => "Array::Array" },
                                         { args => ["substr", "pos"], name => "index" },
                                         {
                                           args    => ["string", "pos", "len"],
                                           name    => "insert",
                                           returns => "String::String",
                                         },
                                         { args => ["delim", "..."], name => "join", returns => "String::String" },
                                         {
                                           args    => [],
                                           doc     => "Lowercases the self string and returns it.",
                                           name    => "lc",
                                           returns => "String::String",
                                         },
                                         { args => [], name => "lcfirst", returns => "String::String" },
                                         { args => [], name => "length", returns => "Number::Number" },
                                         { args => [], name => "ord", returns => "Byte::Byte" },
                                         { args => [], name => "print", returns => "Bool::Bool" },
                                         { args => ["..."], name => "printf", returns => "Bool::Bool" },
                                         { args => [], name => "quotemeta", returns => "String::String" },
                                         { args => [], name => "reverse", returns => "String::String" },
                                         { args => [], name => "say", returns => "Bool::Bool" },
                                         { args => ["sep", "size"], name => "split", returns => "Array::Array" },
                                         { args => ["..."], name => "sprintf", returns => "String::String" },
                                         { args => [], name => "stat_dir", returns => "Glob::Dir" },
                                         {
                                           args    => [],
                                           doc     => "Returns a file object for the self string.",
                                           name    => "stat_file",
                                           returns => "Glob::File",
                                         },
                                         {
                                           args    => ["offs", "len"],
                                           doc     => "Extracts a substring out of the self string and returns it. First character is at offset zero. If I<offs> is negative, starts that far back from the end of the string. If I<len> is omitted, returns everything through the end of the string. If I<len> is negative, leaves that many characters off the end of the string.",
                                           name    => "substr",
                                           returns => "String::String",
                                         },
                                         { args => [], name => "tclc", returns => "String::String" },
                                         {
                                           args    => [],
                                           doc     => "Uppercases the self string and returns it.",
                                           name    => "uc",
                                           returns => "String::String",
                                         },
                                         {
                                           args    => [],
                                           doc     => "Uppercases the first letter of the self string and returns the string.",
                                           name    => "ucfirst",
                                           returns => "String::String",
                                         },
                                         { args => [], name => "unescape", returns => "String::String" },
                                         { args => [], name => "warn" },
                                         { args => [], name => "wordcase", returns => "String::String" },
                                       ],
                         },
             },
}