
=encoding utf8

=head1 NAME

Sidef::Types::Block::Block

=head1 DESCRIPTION

This class implements ...

=head1 SYNOPSIS

var obj = Block(...)


=head1 INHERITS

Inherits methods from:

       * Sidef::Object::Object

=head1 METHODS

=head2 &

    a & b

Returns the

Aliases: I<grep>

=cut

=head2 *

    a * b

Returns the

Aliases: I<repeat>

=cut

=head2 <<

    a << b

Returns the

Aliases: I<for>, I<each>, I<foreach>

=cut

=head2 >>

    a >> b

Returns the

Aliases: I<map>

=cut

=head2 Π

    self.Π(range)

Returns the

Aliases: I<prod>

=cut

=head2 Σ

    self.Σ(range)

Returns the

Aliases: I<sum>

=cut

=head2 ∘

    a ∘ b

Returns the

Aliases: I<compose>

=cut

=head2 array_identity

    self.array_identity

Returns the

=cut

=head2 bsearch

    self.bsearch

Returns the

=cut

=head2 bsearch_ge

    self.bsearch_ge

Returns the

=cut

=head2 bsearch_inverse

    self.bsearch_inverse

Returns the

=cut

=head2 bsearch_le

    self.bsearch_le

Returns the

=cut

=head2 cache

    self.cache

Returns the

=cut

=head2 call

    block.call(*args)

Returns the

=cut

=head2 cap

    self.cap

Returns the

Aliases: I<capture>

=cut

=head2 do

    self.do

Returns the

Aliases: I<run>

=cut

=head2 exec

    self.exec(*args)

Returns the

=cut

=head2 ffork

    self.ffork(*args)

Returns the

Aliases: I<start>

=cut

=head2 first

    self.first(n, range)

Returns the

=cut

=head2 flush_cache

    self.flush_cache

Returns the

=cut

=head2 fork

    self.fork(*args)

Returns the

=cut

=head2 identity

    self.identity

Returns the

=cut

=head2 if

    self.if(bool)

Returns the

=cut

=head2 is_identity

    self.is_identity

Returns the

=cut

=head2 list_identity

    self.list_identity

Returns the

=cut

=head2 loop

    self.loop

Returns the

=cut

=head2 new

    self.new

Returns the

=cut

=head2 nth

    self.nth(n, range)

Returns the

=cut

=head2 null_identity

    self.null_identity

Returns the

=cut

=head2 thr

    self.thr(*args)

Returns the

Aliases: I<thread>

=cut

=head2 time

    self.time

Returns the

=cut

=head2 to_s

    self.to_s

Returns the

Aliases: I<dump>, I<to_str>

=cut

=head2 uncache

    self.uncache

Returns the

=cut

=head2 while

    self.while(condition)

Returns the

=cut
