
=encoding utf8

=head1 NAME

Sidef::Types::Block::Code

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = (Code.new(...));


=head1 INHERITS

Inherits methods from:

	* Sidef

=head1 METHODS


=head2 *

I<Num> B<*> I<Num> -> I<Num>

Return the

=cut

=head2 :

I<Num> B<:> I<Num> -> I<Num>

Return the

=cut

=head2 call

Code.call() -> I<Bool>

Return the

=cut

=head2 do

Code.do() -> I<Bool>

Return the

=cut

=head2 exec

Code.exec() -> I<Bool>

Return the

=cut

=head2 for

Code.for() -> I<Bool>

Return the

=cut

=head2 get_value

Code.get_value() -> I<Bool>

Return the

=cut

=head2 given

Code.given() -> I<Bool>

Return the

=cut

=head2 if

Code.if() -> I<Bool>

Return the

=cut

=head2 repeat

Code.repeat() -> I<Bool>

Return the

=cut

=head2 run

Code.run() -> I<Bool>

Return the

=cut

=head2 toArray

Code.toArray() -> I<Bool>

Return the

=cut

=head2 toHash

Code.toHash() -> I<Bool>

Return the

=cut

=head2 to_array

Code.to_array() -> I<Bool>

Return the

=cut

=head2 to_hash

Code.to_hash() -> I<Bool>

Return the

=cut

=head2 while

Code.while() -> I<Bool>

Return the

=cut
