
=encoding utf8

=head1 NAME

Sidef::Types::Block::Code

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Code.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Object::Object

=head1 METHODS


=head2 *

I<Obj> B<*> I<Obj> -> I<Obj>

Return the

Aliases: I<repeat>

=cut

=head2 all

Code.all() -> I<Obj>

Return the

=cut

=head2 any

Code.any() -> I<Obj>

Return the

=cut

=head2 call

Code.call() -> I<Obj>

Return the

=cut

=head2 cap

Code.cap() -> I<Obj>

Return the

Aliases: I<capture>

=cut

=head2 copy

Code.copy() -> I<Obj>

Return the

Aliases: I<closure>

=cut

=head2 do

Code.do() -> I<Obj>

Return the

Aliases: I<exec>

=cut

=head2 dump

Code.dump() -> I<Obj>

Return the

=cut

=head2 fast_init_block_vars

Code.fast_init_block_vars() -> I<Obj>

Return the

=cut

=head2 for

Code.for() -> I<Obj>

Return the

=cut

=head2 fork

Code.fork() -> I<Obj>

Return the

=cut

=head2 given

Code.given() -> I<Obj>

Return the

=cut

=head2 if

Code.if() -> I<Obj>

Return the

=cut

=head2 init_block_vars

Code.init_block_vars() -> I<Obj>

Return the

=cut

=head2 loop

Code.loop() -> I<Obj>

Return the

=cut

=head2 pfork

Code.pfork() -> I<Obj>

Return the

=cut

=head2 pop_stack

Code.pop_stack() -> I<Obj>

Return the

=cut

=head2 run

Code.run() -> I<Obj>

Return the

=cut

=head2 thr

Code.thr() -> I<Obj>

Return the

Aliases: I<thread>

=cut

=head2 to_array

Code.to_array() -> I<Obj>

Return the

=cut

=head2 to_h

Code.to_h() -> I<Obj>

Return the

Aliases: I<to_hash>

=cut

=head2 try

Code.try() -> I<Obj>

Return the

=cut

=head2 while

Code.while() -> I<Obj>

Return the

=cut
