
=encoding utf8

=head1 NAME

Sidef::Types::Block::Switch

=head1 DESCRIPTION

This object is ...

=head1 SYNOPSIS

var obj = Switch.new(...);


=head1 INHERITS

Inherits methods from:

	* Sidef::Types::Block::Do

=head1 METHODS


=head2 :

I<Obj> B<:> I<Obj> -> I<Obj>

Return the

Aliases: I<else>, I<default>

=cut

=head2 >

I<Obj> B<E<gt>> I<Obj> -> I<Obj>

Return the

Aliases: I<exact>

=cut

=head2 ?

I<Obj> B<?> I<Obj> -> I<Obj>

Return the

Aliases: I<case>

=cut

=head2 end

Switch.end() -> I<Obj>

Return the

=cut

=head2 value

Switch.value() -> I<Obj>

Return the

=cut

=head2 ~

I<Obj> B<~> I<Obj> -> I<Obj>

Return the

Aliases: I<when>

=cut
